/**
 * 红麻
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'country_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Malvaceae(棉葵科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Hibiscus(木槿属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Hibiscus cannabinus L.(红麻)']
	},
	{
		fieldName:'sowingdata',
		chineseName:'播种期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seeding_stage',
		chineseName:'出苗期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'squaring_stage',
		chineseName:'现蕾期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'flowering_stage',
		chineseName:'开花期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'fiber_harvest_time',
		chineseName:'纤维收获期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_days',
		chineseName:'生长天数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[50,162]
	},
	{
		fieldName:'harvesting_date',
		chineseName:'收种期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'total_reproductive_days',
		chineseName:'全生育天数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[85,248]
	},
	{
		fieldName:'shoot_color',
		chineseName:'苗茎色',
		type:'select',
		val:'请选择。。。',
		attach:['淡红','红','黄绿','绿','微红','紫']
	},
	{
		fieldName:'medium_stem_color',
		chineseName:'中茎色',
		type:'select',
		val:'请选择。。。',
		attach:['淡','淡红','红','黄绿','绿','微红','紫']
	},
	{
		fieldName:'posterior_stem_color',
		chineseName:'后茎色',
		type:'select',
		val:'请选择。。。',
		attach:['淡红','红','黄绿','绿','浅绿','微红','紫','紫红']
	},
	{
		fieldName:'leaf_type',
		chineseName:'叶型',
		type:'select',
		val:'请选择。。。',
		attach:['裂','全']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['黄绿','绿','深绿']
	},
	{
		fieldName:'yebingshai',
		chineseName:'叶柄色',
		type:'select',
		val:'请选择。。。',
		attach:['淡红','红','黄','绿','浅红','微红','紫','紫红']
	},
	{
		fieldName:'corolla_color',
		chineseName:'花冠色',
		type:'select',
		val:'请选择。。。',
		attach:['纯黄','红','黄','兰','浅兰','紫','紫红']
	},
	{
		fieldName:'corolla_size',
		chineseName:'花冠大小',
		type:'select',
		val:'请选择。。。',
		attach:['大','小','中']
	},
	{
		fieldName:'throat_color',
		chineseName:'花喉色',
		type:'select',
		val:'请选择。。。',
		attach:['红','黄','紫','紫红']
	},
	{
		fieldName:'calyx_color',
		chineseName:'花萼色',
		type:'select',
		val:'请选择。。。',
		attach:['点红','红','绿']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[150,498]
	},
	{
		fieldName:'stem_diameter',
		chineseName:'茎粗',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.8,2.3]
	},
	{
		fieldName:'fresh_bark_thickness',
		chineseName:'鲜皮厚',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.64,1.83]
	},
	{
		fieldName:'number',
		chineseName:'支数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[126,388]
	},
	{
		fieldName:'pull',
		chineseName:'拉力',
		type:'compare',
		sel:'=',
		val:'',
		attach:[22,51.7]
	},
	{
		fieldName:'fresh_stem_weight',
		chineseName:'株鲜茎重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[90,840]
	},
	{
		fieldName:'plant_fresh_weight',
		chineseName:'株鲜皮重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[24,345]
	},
	{
		fieldName:'plant_dry_weight',
		chineseName:'株干皮重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[18,73]
	},
	{
		fieldName:'fresh_stem_and_dry_skin_rate',
		chineseName:'鲜茎干皮率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6.7,14.5]
	},
	{
		fieldName:'original_jute_weight',
		chineseName:'株原麻重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7,63]
	},
	{
		fieldName:'plant_fine_hemp_weight',
		chineseName:'株精麻重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5,40.8]
	},
	{
		fieldName:'dry_skin_rate',
		chineseName:'干皮精麻率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[34.5,75]
	},
	{
		fieldName:'fiber_yield_per_mu',
		chineseName:'纤维亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[62,275]
	},
	{
		fieldName:'rfy_per_mu',
		chineseName:'原麻亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[120,489]
	},
	{
		fieldName:'refined_yield_per_mu',
		chineseName:'精麻亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[60,260]
	},
	{
		fieldName:'weight',
		chineseName:'种千粒重	',
		type:'compare',
		sel:'=',
		val:'',
		attach:[21,46]
	},
	{
		fieldName:'anthrax',
		chineseName:'炭疽病',
		type:'select',
		val:'请选择。。。',
		attach:['感','抗','强','弱','中']
	},
	{
		fieldName:'root_knot_nematode_disease',
		chineseName:'根结线虫病',
		type:'select',
		val:'请选择。。。',
		attach:['感','抗','弱','中']
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['北京','福建','广东','广西','贵州','国外','湖南','辽宁','山东','台湾','云南','浙江']
	}
]