/**
 * 大麦
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'country_of_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'altitude',
		chineseName:'高程',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4,3840]
	},
	{
		fieldName:'east_longitude',
		chineseName:'东经',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8513,12628]
	},
	{
		fieldName:'north_latitude',
		chineseName:'北纬',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2533,4357]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Gramineae(禾本科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Hordeum(大麦属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Hordeum vulgare (L.) Hsu(普通大麦)']
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'breeding_unit',
		chineseName:'选育单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'a_pedigree',
		chineseName:'系谱',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'rowtype',
		chineseName:'棱型',
		type:'select',
		val:'请选择。。。',
		attach:['二','六','四','中']
	},
	{
		fieldName:'bare_skin',
		chineseName:'皮裸',
		type:'select',
		val:'请选择。。。',
		attach:['裸','皮']
	},
	{
		fieldName:'awn_shaped',
		chineseName:'芒形',
		type:'select',
		val:'请选择。。。',
		attach:['长','长钩','等穗','短','钩芒','微芒','无芒','中长侧短','中长侧短钩','中长侧无','中短侧微','中短侧无']
	},
	{
		fieldName:'awn',
		chineseName:'芒性',
		type:'select',
		val:'请选择。。。',
		attach:['齿','光']
	},
	{
		fieldName:'panicle_and_awn_colour',
		chineseName:'穗和芒色',
		type:'select',
		val:'请选择。。。',
		attach:['黑','黄','灰','紫']
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['淡黄','淡蓝','褐','黑','黑褐','黄','黄褐','黄蓝','灰','蓝','绿','紫']
	},
	{
		fieldName:'shell_color',
		chineseName:'壳色',
		type:'select',
		val:'请选择。。。',
		attach:['淡黄','黑','黄','灰','紫']
	},
	{
		fieldName:'quality',
		chineseName:'品质',
		type:'select',
		val:'请选择。。。',
		attach:['半硬','软','中','下','硬']
	},
	{
		fieldName:'panicle_density',
		chineseName:'穗密度',
		type:'select',
		val:'请选择。。。',
		attach:['密','疏','软']
	},
	{
		fieldName:'spring_and_winter',
		chineseName:'冬春性',
		type:'select',
		val:'请选择。。。',
		attach:['半冬','春','冬']
	},
	{
		fieldName:'locally_mature_type',
		chineseName:'当地成熟型',
		type:'select',
		val:'请选择。。。',
		attach:['极晚','极早','晚','早','中']
	},
	{
		fieldName:'tillering_ability',
		chineseName:'分蘖力',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[43,166]
	},
	{
		fieldName:'grain_number_per_panicle',
		chineseName:'穗粒数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6.3,96]
	},
	{
		fieldName:'thousand_grain_weight',
		chineseName:'千粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5.5,66.8]
	},
	{
		fieldName:'crude_protein',
		chineseName:'粗蛋白',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7.05,23.11]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.18,0.65]
	},
	{
		fieldName:'total_starch',
		chineseName:'总淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[11.57,69.26]
	},
	{
		fieldName:'whole_meal_extract',
		chineseName:'全粉浸出物',
		type:'compare',
		sel:'=',
		val:'',
		attach:[67,82.4]
	},
	{
		fieldName:'saccharifying_power',
		chineseName:'糖化力',
		type:'compare',
		sel:'=',
		val:'',
		attach:[143.64,397.77]
	},
	{
		fieldName:'percentage_difference_of_water_sensitivity',
		chineseName:'水敏百分差',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'water_sensitivity',
		chineseName:'水敏称度',
		type:'select',
		val:'请选择。。。',
		attach:['极轻']
	},
	{
		fieldName:'percentage_of_scab',
		chineseName:'赤霉病穗率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.3,100]
	},
	{
		fieldName:'fusarium_head_blight_index',
		chineseName:'赤霉病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.5,97.5]
	},
	{
		fieldName:'scab_resistance',
		chineseName:'赤霉病抗性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'incidence_of_yellow_flower',
		chineseName:'黄花发病率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,100]
	},
	{
		fieldName:'yellow_degree_of_yellow_flower',
		chineseName:'黄花黄化度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,3]
	},
	{
		fieldName:'yellow_mosaic_resistance',
		chineseName:'黄花叶抗性',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','R','S']
	},
	{
		fieldName:'stripe_disease_rate',
		chineseName:'条纹病病率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,100]
	},
	{
		fieldName:'stripe_resistance',
		chineseName:'条纹病抗性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'yellow_dwarf_severity',
		chineseName:'黄矮严重度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,9]
	},
	{
		fieldName:'drought_resistance_level',
		chineseName:'抗旱级别',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'salt_tolerance_level',
		chineseName:'耐盐级别',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'waterlogging_tolerance_level',
		chineseName:'耐涝级别',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['北京','贵州','国外','湖北','湖南','吉林','江苏','青海','四川','西藏','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育','野生']
	},
]