/**
 * 蚕豆
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family_name',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Leguminosae(豆科)']
	},
	{
		fieldName:'generic_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Vicia(巢菜属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Vicia faba L.(蚕豆)']
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'country_of_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'sowing_date',
		chineseName:'播种期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.05,11.28]
	},
	{
		fieldName:'mature_period',
		chineseName:'成熟期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.04,9.22]
	},
	{
		fieldName:'maturity',
		chineseName:'熟性',
		type:'select',
		val:'请选择。。。',
		attach:['晚','早','中']
	},
	{
		fieldName:'total_reproductive_days',
		chineseName:'全生育日数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[76,251]
	},
	{
		fieldName:'color',
		chineseName:'花色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白淡','褐','浅红','浅紫','深紫','紫']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10.3,192]
	},
	{
		fieldName:'effective_branch',
		chineseName:'有效枝',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,10.4]
	},
	{
		fieldName:'pod_number_per_plant',
		chineseName:'单株荚数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.1,93.7]
	},
	{
		fieldName:'number_of_pods_per_pod',
		chineseName:'单荚粒数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.8,50.4]
	},
	{
		fieldName:'grain_weight_per_plant',
		chineseName:'单株产量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.3,230.9]
	},
	{
		fieldName:'pod_length',
		chineseName:'荚长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.2,18.8]
	},
	{
		fieldName:'pod_width',
		chineseName:'荚宽',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.7,8.5]
	},
	{
		fieldName:'grain_type',
		chineseName:'粒型',
		type:'select',
		val:'请选择。。。',
		attach:['大','小','中']
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白底黑斑','褐','黑','红','灰','绿','浅红','浅黄','浅绿','浅紫','乳白','深绿','紫','紫红']
	},
	{
		fieldName:'grain_shape',
		chineseName:'粒形',
		type:'select',
		val:'请选择。。。',
		attach:['薄','长厚','大','短薄','短厚','短圆','厚','宽薄','宽扁','宽厚','阔薄','阔厚','中阔','球形','圆','窄薄','窄厚','中薄','中等','中厚']
	},
	{
		fieldName:'evenness',
		chineseName:'均匀度',
		type:'select',
		val:'请选择。。。',
		attach:['不均','较均','均匀','中']
	},
	{
		fieldName:'grain_weight',
		chineseName:'百粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6,240]
	},
	{
		fieldName:'crude_protein',
		chineseName:'粗蛋白',
		type:'compare',
		sel:'=',
		val:'',
		attach:[17.65,34.52]
	},
	{
		fieldName:'crude_fat',
		chineseName:'粗脂肪',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.52,2.8]
	},
	{
		fieldName:'total_starch',
		chineseName:'总淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10.34,53.36]
	},
	{
		fieldName:'amylose',
		chineseName:'直链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6,27.92]
	},
	{
		fieldName:'amylopectin',
		chineseName:'支链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[11.51,42.25]
	},
	{
		fieldName:'salt_tolerance_at_bud_stage',
		chineseName:'芽期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'salt_tolerance_in_seedling_stage',
		chineseName:'苗期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,5]
	},
	{
		fieldName:'flood_resistance',
		chineseName:'抗涝性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'brown_spot',
		chineseName:'褐斑病级',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'brown_spot_index',
		chineseName:'褐斑病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[16.7,100]
	},
	{
		fieldName:'brown_spot_assessment',
		chineseName:'褐斑病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','MS','S']
	},
	{
		fieldName:'red_spot_disease',
		chineseName:'赤斑病级',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'white_spot_disease_index',
		chineseName:'赤斑病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[26.8,100]
	},
	{
		fieldName:'white_spot_disease_evaluation',
		chineseName:'赤斑病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','MS','S']
	},
	{
		fieldName:'rust_class',
		chineseName:'锈病病级',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'rust_index',
		chineseName:'锈病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12.6,100]
	},
	{
		fieldName:'rust_evaluation',
		chineseName:'锈病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','MS','R','S']
	},
	{
		fieldName:'aphid_sick_level',
		chineseName:'蚜害病级',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,9]
	},
	{
		fieldName:'the_sick_aphid_index',
		chineseName:'蚜害病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[18,100]
	},
	{
		fieldName:'evaluation_of_diseased_aphids',
		chineseName:'蚜害病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','R','S']
	},
	{
		fieldName:'aspartic_acid',
		chineseName:'天冬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.07,3.86]
	},
	{
		fieldName:'threonine',
		chineseName:'苏氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.58,1.19]
	},
	{
		fieldName:'serine',
		chineseName:'丝氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.32,1.59]
	},
	{
		fieldName:'glutamate',
		chineseName:'谷氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.28,6.68]
	},
	{
		fieldName:'glycine',
		chineseName:'甘氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.88,1.5]
	},
	{
		fieldName:'alanine',
		chineseName:'丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.98,1.5]
	},
	{
		fieldName:'cystine',
		chineseName:'胱氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.06,1.28]
	},
	{
		fieldName:'valine',
		chineseName:'缬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.99,1.86]
	},
	{
		fieldName:'methionine',
		chineseName:'蛋氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.06,1.26]
	},
	{
		fieldName:'isoleucine',
		chineseName:'异亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.88,1.78]
	},
	{
		fieldName:'leucine',
		chineseName:'亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.47,2.78]
	},
	{
		fieldName:'tyrosine',
		chineseName:'酪氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.47,1.17]
	},
	{
		fieldName:'phenylalanine',
		chineseName:'苯丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.24,1.91]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.37,2.3]
	},
	{
		fieldName:'histidine',
		chineseName:'组氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.26,1.04]
	},
	{
		fieldName:'arginine',
		chineseName:'精氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.53,4.33]
	},
	{
		fieldName:'proline',
		chineseName:'脯氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.44,2.3]
	},
	{
		fieldName:'typtophan',
		chineseName:'色氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.009,0.23]
	},
	{
		fieldName:'the_sum',
		chineseName:'总和',
		type:'compare',
		sel:'=',
		val:'',
		attach:[18.02,32.85]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育']
	},
]