/**
 * 白菜
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Cruciferae(十字花科)']
	},
	{
		fieldName:'the_genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Brassica(芸薹属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Brassica campestris L. ssp. chinensis var. communis(白菜)']
	},
	{
		fieldName:'breed_origin',
		chineseName:'品种来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'propagation_unit',
		chineseName:'繁种单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'unit_number',
		chineseName:'单位编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_phase',
		chineseName:'生长期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[29,240]
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8,82.5]
	},
	{
		fieldName:'strain_amplitude',
		chineseName:'株幅',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'plant_type',
		chineseName:'株型',
		type:'select',
		val:'请选择。。。',
		attach:['半开展','半平展','半塌地','半直立','开展','平展','束腰','塌地','直立','榻地']
	},
	{
		fieldName:'lobate',
		chineseName:'叶形',
		type:'select',
		val:'请选择。。。',
		attach:['长倒卵','长卵','长卵圆','长椭圆','长圆','匙形','倒卵','倒卵圆','短椭圆','花叶','近扁','近圆','葵扇形','阔倒卵','卵形','卵圆','披针','扇形','束腰','椭圆']
	},
	{
		fieldName:'leaf_margin',
		chineseName:'叶缘',
		type:'select',
		val:'请选择。。。',
		attach:['波状','锯齿','全缘']
	},
	{
		fieldName:'leaf_lobes',
		chineseName:'叶裂刻',
		type:'select',
		val:'请选择。。。',
		attach:['浅裂','全裂','深裂','无裂刻']
	},
	{
		fieldName:'leaf',
		chineseName:'叶面',
		type:'select',
		val:'请选择。。。',
		attach:['多皱','较平','平滑','微皱','中皱','皱','皱缩']
	},
	{
		fieldName:'facial_bristle',
		chineseName:'叶面刺毛',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','无','中']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['白绿','淡绿','黑绿','黄绿','灰绿','绿','绿白','墨绿','浅黄白','浅黄绿','浅绿','深绿','外绿心','乌绿','紫红','紫绿']
	},
	{
		fieldName:'leaf_length',
		chineseName:'叶长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10,65]
	},
	{
		fieldName:'leaf_width',
		chineseName:'叶宽',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.5,33]
	},
	{
		fieldName:'petiole_color',
		chineseName:'叶柄色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白绿','浅绿','黄绿','绿','绿白','浅绿','浅绿白','青或白','深绿','紫红','紫']
	},
	{
		fieldName:'petiole_length',
		chineseName:'叶柄长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,50]
	},
	{
		fieldName:'petiole_width',
		chineseName:'叶柄宽',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.4,27]
	},
	{
		fieldName:'petiole_thick',
		chineseName:'叶柄厚',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,17]
	},
	{
		fieldName:'individual_weight',
		chineseName:'单株重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12,2750]
	},
	{
		fieldName:'seed_thousand_grain_weight',
		chineseName:'种子千粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,4.5]
	},
	{
		fieldName:'fiber_content',
		chineseName:'纤维含量',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'quality',
		chineseName:'品质',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'purpose',
		chineseName:'用途',
		type:'select',
		val:'请选择。。。',
		attach:['熟食','熟食干制','熟食腌制','熟食腌制干制','腌制']
	},
	{
		fieldName:'maturity',
		chineseName:'熟性',
		type:'select',
		val:'请选择。。。',
		attach:['极晚','极早','晚','早','中','中晚','中早']
	},
	{
		fieldName:'storability',
		chineseName:'贮藏性',
		type:'select',
		val:'请选择。。。',
		attach:['差','强','中']
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cold_tolerance',
		chineseName:'耐寒性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'drought_tolerance',
		chineseName:'耐旱性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'heat_resistance',
		chineseName:'耐热性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'waterlogging_resistance',
		chineseName:'耐涝性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'disease_resistance',
		chineseName:'抗病性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'insect_resistance',
		chineseName:'抗虫性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivation_period',
		chineseName:'栽培时期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'sowing_date',
		chineseName:'播种期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'colonization_period',
		chineseName:'定植期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'harvest_time',
		chineseName:'收获期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'yield',
		chineseName:'单产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[500,95000]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
]