/**
 * 胡萝卜
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Umbelliferae(伞形花科)']
	},
	{
		fieldName:'the_genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Daucus(胡萝卜属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Daucus carota L. var sativa DC.(胡萝卜)']
	},
	{
		fieldName:'breed_origin',
		chineseName:'品种来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'propagation_unit',
		chineseName:'繁种单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'unit_number',
		chineseName:'单位编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_phase',
		chineseName:'生长期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[62,180]
	},
	{
		fieldName:'frondage',
		chineseName:'叶簇',
		type:'select',
		val:'请选择。。。',
		attach:['半直立','较平展','平展','直立']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['黄绿','绿','浅绿','深绿','紫']
	},
	{
		fieldName:'leaf_pubescence',
		chineseName:'叶面茸毛',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'petiole_of_color',
		chineseName:'叶柄色',
		type:'select',
		val:'请选择。。。',
		attach:['绿','浅绿','浅紫','深绿','紫','紫红','紫绿']
	},
	{
		fieldName:'petiole_pubescence',
		chineseName:'叶柄茸毛',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'fleshy_root_length',
		chineseName:'肉质根长',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'fleshy_root_rough',
		chineseName:'肉质根粗',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'fleshy_root',
		chineseName:'肉质根形',
		type:'select',
		val:'请选择。。。',
		attach:['长圆筒','长圆柱','长圆锥','短圆筒','短圆柱','短圆锥','圆筒','圆柱','圆锥']
	},
	{
		fieldName:'root_shoulder_size',
		chineseName:'根肩部大小',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'dangenzhong',
		chineseName:'单根重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[50,875]
	},
	{
		fieldName:'the_root_color',
		chineseName:'根皮色',
		type:'select',
		val:'请选择。。。',
		attach:['橙红','橙红黄','橙黄','大红','红','黄','黄橙','黄橙红','桔红','桔黄','浅橙','浅红','浅黄','浅桔红','浅桔黄','紫','紫红']
	},
	{
		fieldName:'root_flesh_color',
		chineseName:'根肉色',
		type:'select',
		val:'请选择。。。',
		attach:['白','橙红','橙黄','红','黄','黄白','黄红','桔红','桔黄','浅橙红','浅黄','浅桔黄','紫红']
	},
	{
		fieldName:'root_pulp_color',
		chineseName:'根髓色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白黄','橙红','橙黄','红','黄','黄白','黄红','黄绿','桔红','桔黄','浅橙','浅红','浅黄','浅桔黄','浅紫红','深黄']
	},
	{
		fieldName:'root_pulp_size',
		chineseName:'根髓大小',
		type:'select',
		val:'请选择。。。',
		attach:['大','下','小','中']
	},
	{
		fieldName:'flavor',
		chineseName:'风味',
		type:'select',
		val:'请选择。。。',
		attach:['淡','浓','稍甜','甜','中']
	},
	{
		fieldName:'root_meat',
		chineseName:'根肉质',
		type:'select',
		val:'请选择。。。',
		attach:['粗','脆','脆嫩','嫩脆','疏松','松','细嫩','致密','艮硬']
	},
	{
		fieldName:'root_meat_taste',
		chineseName:'根肉口感',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'root_water_content',
		chineseName:'根肉水分',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','中']
	},
	{
		fieldName:'purpose',
		chineseName:'用途',
		type:'select',
		val:'请选择。。。',
		attach:['加工','生食','生熟','熟食']
	},
	{
		fieldName:'maturity',
		chineseName:'熟性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'storability',
		chineseName:'贮藏性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cold_tolerance',
		chineseName:'耐寒性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'drought_tolerance',
		chineseName:'耐旱性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'heat_resistance',
		chineseName:'耐热性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'waterlogging_resistance',
		chineseName:'耐涝性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'disease_resistance',
		chineseName:'抗病性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'insect_resistance',
		chineseName:'抗虫性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivation_period',
		chineseName:'栽培时期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'sowing_date',
		chineseName:'播种期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'harvest_time',
		chineseName:'收获期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'yield',
		chineseName:'单产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[750,8000]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
]