/**
 * 芹菜
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_stage',
		chineseName:'生育期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[55,300]
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[27,120]
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['绿','淡绿','深绿']
	},
	{
		fieldName:'petiole_length',
		chineseName:'叶柄长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.8,354]
	},
	{
		fieldName:'there',
		chineseName:'叶柄宽',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.2,26.5]
	},
	{
		fieldName:'thickness',
		chineseName:'叶柄厚',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,28]
	},
	{
		fieldName:'petiole_thick',
		chineseName:'叶柄断面',
		type:'select',
		val:'请选择。。。',
		attach:['半空心','空心','实心']
	},
	{
		fieldName:'yebingshai',
		chineseName:'叶柄色',
		type:'select',
		val:'请选择。。。',
		attach:['白','绿','浅黄','浅绿','深绿']
	},
	{
		fieldName:'individual_weight',
		chineseName:'单株重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[9,975]
	},
	{
		fieldName:'petiole_meat',
		chineseName:'叶柄肉质',
		type:'select',
		val:'请选择。。。',
		attach:['脆嫩','多纤维','中等']
	},
	{
		fieldName:'flavor',
		chineseName:'风味',
		type:'select',
		val:'请选择。。。',
		attach:['淡','较浓','浓','中']
	},
	{
		fieldName:'cultivation_season',
		chineseName:'栽培季节',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'disease_resistance_and_insect_resistance',
		chineseName:'抗病虫性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'per_mu_yield',
		chineseName:'亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[500,8750]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
]