/**
 * 香菜
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_stage',
		chineseName:'生育期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[35,180]
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7,45]
	},
	{
		fieldName:'strain_amplitude',
		chineseName:'株幅',
		type:'compare',
		sel:'=',
		val:'',
		attach:[13.5,34.4]
	},
	{
		fieldName:'leaf_length',
		chineseName:'叶长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,33]
	},
	{
		fieldName:'leaf_width',
		chineseName:'叶宽',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.5,8.3]
	},
	{
		fieldName:'petiole_length',
		chineseName:'叶柄长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4.9,20.8]
	},
	{
		fieldName:'leaf_number_per_plant',
		chineseName:'单株叶数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6.9,16]
	},
	{
		fieldName:'lobate',
		chineseName:'叶形',
		type:'select',
		val:'请选择。。。',
		attach:['长卵','卵圆','园形','圆形']
	},
	{
		fieldName:'leaf_margin',
		chineseName:'叶缘',
		type:'select',
		val:'请选择。。。',
		attach:['浅缺刻','深缺刻']
	},
	{
		fieldName:'leaf',
		chineseName:'叶面',
		type:'select',
		val:'请选择。。。',
		attach:['平滑']
	},
	{
		fieldName:'leaf_angle',
		chineseName:'叶角',
		type:'select',
		val:'请选择。。。',
		attach:['半直立']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['绿','浅绿','深绿']
	},
	{
		fieldName:'petiole_color',
		chineseName:'叶柄色',
		type:'select',
		val:'请选择。。。',
		attach:['绿','浅绿','浅紫','深紫','紫']
	},
	{
		fieldName:'individual_weight',
		chineseName:'单株重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.5,50]
	},
	{
		fieldName:'cultivation_season',
		chineseName:'栽培季节',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'disease_resistance_and_insect_resistance',
		chineseName:'抗病虫性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'per_mu_yield',
		chineseName:'亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[225,8000]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
]