/**
 * 棉花
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'year',
		chineseName:'年',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1986,1995]
	},
	{
		fieldName:'category',
		chineseName:'类别',
		type:'select',
		val:'请选择。。。',
		attach:['非洲棉','海国内','海国外','陆半野','陆国内','陆国外','陆遗传','亚洲棉','其它棉']
	},
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_origin',
		chineseName:'种子来源地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'altitude',
		chineseName:'高程',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,4611]
	},
	{
		fieldName:'east_longitude',
		chineseName:'东经',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7559,12321]
	},
	{
		fieldName:'north_latitude',
		chineseName:'北纬',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2209,4425]
	},
	{
		fieldName:'country_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'select',
		val:'请选择。。。',
		attach:['巴州农科所','河北棉花所','湖北经作所','江苏经作所','辽宁经作所','山西棉花所','吐鲁番地区所','新疆巴州农科所','中棉所']
	},
	{
		fieldName:'unit_number',
		chineseName:'单位编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Malvaceae(棉葵科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Gossypium L.(棉属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Gossypium anomalum Wawr. & Peyr.(异常棉)','Gossypium arboreum L.(亚洲棉)','Gossypium aridum Skov.(旱地棉)','Gossypium barbadense L.(海岛棉)','Gossypium barbosanum(长须棉)','Gossypium capitis-viridis Mauer(绿顶棉)','Gossypium darwinii Watt(达尔文氏棉)','Gossypium davidsonii Kell.(戴维逊氏棉)','Gossypium gossypioides Standl.(拟似棉)','Gossypium herbaceum var. africanum(非洲棉变种)','Gossypium hirsutum L.(陆地棉)','Gossypium klotzschianum Andress.(克劳次基棉)','Gossypium lanceolatum Tod.(茅叶棉)','Gossypium ralmondii Ulbr.(雷蒙德氏棉)','Gossypium stocksii Mast. ex Hook.(斯托克西棉)','Gossypium thurberi Tod.(瑟伯氏棉)','Gossypium trilobum Skov.(三裂棉)']
	},
	{
		fieldName:'growth_stage',
		chineseName:'生育期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[94,211]
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10.7,320]
	},
	{
		fieldName:'growth_vigor',
		chineseName:'生长势',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'plant_type',
		chineseName:'株形',
		type:'select',
		val:'请选择。。。',
		attach:['丛','塔','筒']
	},
	{
		fieldName:'branch_node',
		chineseName:'果枝节位',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,20]
	},
	{
		fieldName:'number_fruit_branch',
		chineseName:'果枝数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,49.2]
	},
	{
		fieldName:'yezhishu',
		chineseName:'叶枝数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,19]
	},
	{
		fieldName:'fruit_type',
		chineseName:'果枝类型',
		type:'select',
		val:'请选择。。。',
		attach:['0','1','2','3','4']
	},
	{
		fieldName:'branch_extension_angle',
		chineseName:'果枝伸展角',
		type:'select',
		val:'请选择。。。',
		attach:['<45','=45','>45']
	},
	{
		fieldName:'stem_color',
		chineseName:'茎色',
		type:'select',
		val:'请选择。。。',
		attach:['红','绿','青','紫']
	},
	{
		fieldName:'stem_hairs',
		chineseName:'茎毛',
		type:'select',
		val:'请选择。。。',
		attach:['多','中','少','无']
	},
	{
		fieldName:'main_stem_thickness',
		chineseName:'主茎粗细',
		type:'select',
		val:'请选择。。。',
		attach:['粗','细','中']
	},
	{
		fieldName:'stem_hardness',
		chineseName:'主茎硬度',
		type:'select',
		val:'请选择。。。',
		attach:['软','硬','中']
	},
	{
		fieldName:'lodging',
		chineseName:'倒伏性',
		type:'select',
		val:'请选择。。。',
		attach:['不倒','倒']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['淡绿','红','花斑','黄','黄绿','灰绿','绿','绿红','深绿','紫','紫红']
	},
	{
		fieldName:'blade_size',
		chineseName:'叶片大小',
		type:'select',
		val:'请选择。。。',
		attach:['大','小','中']
	},
	{
		fieldName:'leaf',
		chineseName:'叶形',
		type:'select',
		val:'请选择。。。',
		attach:['超鸡脚','鸡脚','皱缩','阔叶','心脏']
	},
	{
		fieldName:'leaf_thickness',
		chineseName:'叶厚度',
		type:'select',
		val:'请选择。。。',
		attach:['薄','厚','中']
	},
	{
		fieldName:'yemixian',
		chineseName:'叶蜜腺',
		type:'select',
		val:'请选择。。。',
		attach:['无','有']
	},
	{
		fieldName:'cotton_toxin',
		chineseName:'棉毒素',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','无','中']
	},
	{
		fieldName:'villi',
		chineseName:'叶绒毛',
		type:'select',
		val:'请选择。。。',
		attach:['长','短','中','无','多','少']
	},
	{
		fieldName:'corolla_color',
		chineseName:'花冠色',
		type:'select',
		val:'请选择。。。',
		attach:['白','淡红','淡黄','粉红','红','红白','黄','黄白','黄绿','紫红','鲜黄','乳白','乳黄','鲜红']
	},
	{
		fieldName:'flower_size',
		chineseName:'花大小',
		type:'select',
		val:'请选择。。。',
		attach:['大','小','中']
	},
	{
		fieldName:'flower_core_color',
		chineseName:'花芯色',
		type:'select',
		val:'请选择。。。',
		attach:['白','淡黄','红','红心','黄','黄白','黄红','乳白','乳黄','无','鲜黄','紫','紫红']
	},
	{
		fieldName:'anther_color',
		chineseName:'花药色',
		type:'select',
		val:'请选择。。。',
		attach:['白','淡黄','红','红白','黄','金黄','黄红','黄白','乳白','乳黄']
	},
	{
		fieldName:'style_length',
		chineseName:'花柱长',
		type:'select',
		val:'请选择。。。',
		attach:['等于','低于','高于']
	},
	{
		fieldName:'bract_shape',
		chineseName:'苞叶形状',
		type:'select',
		val:'请选择。。。',
		attach:['披针','心脏','窄卷']
	},
	{
		fieldName:'bracts_herbaceous',
		chineseName:'苞外蜜腺',
		type:'select',
		val:'请选择。。。',
		attach:['无','有']
	},
	{
		fieldName:'boll_forming_method',
		chineseName:'铃着生方式',
		type:'select',
		val:'请选择。。。',
		attach:['半丛','丛生','单生','双生']
	},
	{
		fieldName:'color_bell',
		chineseName:'铃色',
		type:'select',
		val:'请选择。。。',
		attach:['红','红绿','绿','深绿','紫红']
	},
	{
		fieldName:'bell_shaped',
		chineseName:'铃形',
		type:'select',
		val:'请选择。。。',
		attach:['长卵圆','卵圆','圆','圆锥']
	},
	{
		fieldName:'bell_shank_length',
		chineseName:'铃柄长',
		type:'select',
		val:'请选择。。。',
		attach:['长','短','中']
	},
	{
		fieldName:'boll_cracking',
		chineseName:'铃开裂',
		type:'select',
		val:'请选择。。。',
		attach:['不畅','畅']
	},
	{
		fieldName:'boll_chamber_number',
		chineseName:'铃室数',
		type:'select',
		val:'请选择。。。',
		attach:['=3','>3']
	},
	{
		fieldName:'boll_number_per_plant',
		chineseName:'单株铃数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,41.5]
	},
	{
		fieldName:'boll_weight',
		chineseName:'铃重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.4,9.81]
	},
	{
		fieldName:'seed_villus',
		chineseName:'种子绒毛',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','无','稀','有','中']
	},
	{
		fieldName:'linter_color',
		chineseName:'短绒色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白光','白绿','光','杂','褐','灰','灰绿','绿','绿棕','浅绿','棕','棕绿']
	},
	{
		fieldName:'cotton_color',
		chineseName:'絮棉色',
		type:'select',
		val:'请选择。。。',
		attach:['白','褐','绿','浅棕','乳黄','棕']
	},
	{
		fieldName:'lint_percentage',
		chineseName:'衣分',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4.2,47.32]
	},
	{
		fieldName:'seed_index',
		chineseName:'子指',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.8,27.7]
	},
	{
		fieldName:'impurity_level',
		chineseName:'杂质等级',
		type:'select',
		val:'请选择。。。',
		attach:['1','2','3','4','5','6']
	},
	{
		fieldName:'long_span',
		chineseName:'跨长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10,37.2]
	},
	{
		fieldName:'length_uniformity',
		chineseName:'长度整齐度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[37.3,56.9]
	},
	{
		fieldName:'specific_strength',
		chineseName:'比强度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7,35.9]
	},
	{
		fieldName:'percentage_elongation',
		chineseName:'伸长百分率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.7,12]
	},
	{
		fieldName:'clone_value',
		chineseName:'麦克隆值',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.9,8.6]
	},
	{
		fieldName:'light_reflectivity',
		chineseName:'光反射率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[50.3,80.7]
	},
	{
		fieldName:'whiteness',
		chineseName:'白度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6.1,15.2]
	},
	{
		fieldName:'color_and_lustre',
		chineseName:'色泽',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'ring_spinning_strength',
		chineseName:'环纺纱强力',
		type:'compare',
		sel:'=',
		val:'',
		attach:[27,187]
	},
	{
		fieldName:'ring_spinning_number',
		chineseName:'环纺纱号数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,17]
	},
	{
		fieldName:'rotor_spinning_index',
		chineseName:'气流纺指标',
		type:'compare',
		sel:'=',
		val:'',
		attach:[843,2586]
	},
	{
		fieldName:'air_yarn_count',
		chineseName:'气流纱支数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,10]
	},
	{
		fieldName:'kernel_fat',
		chineseName:'种仁脂肪',
		type:'compare',
		sel:'=',
		val:'',
		attach:[25.5,43.8]
	},
	{
		fieldName:'seed_protein',
		chineseName:'种仁蛋白',
		type:'compare',
		sel:'=',
		val:'',
		attach:[25.7,48.9]
	},
	{
		fieldName:'gossypol',
		chineseName:'棉酚',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.0032,1.2719]
	},
	{
		fieldName:'Tannin',
		chineseName:'单宁',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.03557,0.1522]
	},
	{
		fieldName:'drought_tolerance',
		chineseName:'耐旱性',
		type:'select',
		val:'请选择。。。',
		attach:['不抗','高抗','抗']
	},
	{
		fieldName:'waterlogging_resistance',
		chineseName:'耐涝性',
		type:'select',
		val:'请选择。。。',
		attach:['不耐','高耐','较耐','耐']
	},
	{
		fieldName:'salt_tolerance',
		chineseName:'耐盐性',
		type:'select',
		val:'请选择。。。',
		attach:['不抗','高抗','抗']
	},
	{
		fieldName:'wilt',
		chineseName:'枯萎病',
		type:'select',
		val:'请选择。。。',
		attach:['HR','I','R','S','T']
	},
	{
		fieldName:'verticillium_wilt',
		chineseName:'黄萎病',
		type:'select',
		val:'请选择。。。',
		attach:['HR','R','S','T']
	},
	{
		fieldName:'bollworm',
		chineseName:'棉铃虫',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'pink_bollworm',
		chineseName:'红铃虫',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'aphid',
		chineseName:'蚜虫',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'cotton_spider_mite',
		chineseName:'棉红蜘蛛',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育']
	},
]