/**
 * 黄瓜
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'maturity',
		chineseName:'熟性',
		type:'select',
		val:'请选择。。。',
		attach:['晚','早','中']
	},
	{
		fieldName:'growth_habit',
		chineseName:'生长习性',
		type:'select',
		val:'请选择。。。',
		attach:['矮生','半蔓生','蔓生','攀援蔓生','匍匐蔓生']
	},
	{
		fieldName:'branching',
		chineseName:'分枝性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'leaf',
		chineseName:'叶形',
		type:'select',
		val:'请选择。。。',
		attach:['其他','心形','圆形','掌形']
	},
	{
		fieldName:'female_flower_node_position',
		chineseName:'雌首花节位',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.20]
	},
	{
		fieldName:'melon_shaped',
		chineseName:'瓜形',
		type:'select',
		val:'请选择。。。',
		attach:['扁圆形','长曲条','梨形','椭圆形','弯颈形','弯曲条','细长条','哑铃型','圆柱形']
	},
	{
		fieldName:'taking_the_melon',
		chineseName:'商瓜皮色',
		type:'select',
		val:'请选择。。。',
		attach:['白','黄','灰','绿','奶油色']
	},
	{
		fieldName:'guar_stripe',
		chineseName:'商瓜斑纹',
		type:'select',
		val:'请选择。。。',
		attach:['斑块状','条带状','线条状']
	},
	{
		fieldName:'commercial_melon_inferior_color',
		chineseName:'商瓜次色',
		type:'select',
		val:'请选择。。。',
		attach:['白色','黄色','绿色','奶油色']
	},
	{
		fieldName:'old_melon',
		chineseName:'老瓜皮色',
		type:'select',
		val:'请选择。。。',
		attach:['暗绿','褐色','黑色','红色','黄白','黄色','灰色','桔黄色','绿色','奶油色']
	},
	{
		fieldName:'melon_markings',
		chineseName:'老瓜斑纹',
		type:'select',
		val:'请选择。。。',
		attach:['斑纹','网蚊','网纹','纹']
	},
	{
		fieldName:'old_melon_next_color',
		chineseName:'老瓜次色',
		type:'select',
		val:'请选择。。。',
		attach:['白色']
	},
	{
		fieldName:'edge_shape',
		chineseName:'瓜棱形状',
		type:'select',
		val:'请选择。。。',
		attach:['具刺','具瘤','棱','平','浅波状','网状']
	},
	{
		fieldName:'number_of_melon_spines',
		chineseName:'瓜刺多少',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','无','中']
	},
	{
		fieldName:'melon_thorn_color',
		chineseName:'瓜刺色',
		type:'select',
		val:'请选择。。。',
		attach:['白','黑','灰','棕']
	},
	{
		fieldName:'noodles_with_melon_flour',
		chineseName:'瓜面腊粉',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','无','中']
	},
	{
		fieldName:'single_melon_weight',
		chineseName:'单瓜重',
		type:'select',
		val:'请选择。。。',
		attach:[0.1,2.5]
	},
	{
		fieldName:'meat_quality',
		chineseName:'肉质',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'flavor',
		chineseName:'风味',
		type:'select',
		val:'请选择。。。',
		attach:['淡而无味','苦','涩','酸','甜','中','微甜','香']
	},
	{
		fieldName:'cultivation_season',
		chineseName:'栽培季节',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'per_mu_yield',
		chineseName:'亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[200,8000]
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'incidence_of_epidemic_disease',
		chineseName:'疫病发病率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,100]
	},
	{
		fieldName:'blight_resistance',
		chineseName:'疫病抗指',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.01,86]
	},
	{
		fieldName:'wilt_incidence',
		chineseName:'枯萎发病率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,100]
	},
	{
		fieldName:'blight',
		chineseName:'枯萎病抗指',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.001,10.76]
	},
	{
		fieldName:'incidence_of_downy_mildew',
		chineseName:'霜霉发病率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[19,100]
	},
	{
		fieldName:'downy_mildew_resistance',
		chineseName:'霜霉病抗指',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.01,11.04]
	},
	{
		fieldName:'incidence_of_white_powder',
		chineseName:'白粉发病率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,100]
	},
	{
		fieldName:'powdery_mildew_resistance',
		chineseName:'白粉病抗指',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.001,89]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
]