/**
 * 亚麻
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'variety_code',
		chineseName:'品种代号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'country_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Linaceae(亚麻科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Linum(亚麻属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Linum usitatissimum L.(亚麻)']
	},
	{
		fieldName:'type',
		chineseName:'类型',
		type:'select',
		val:'请选择。。。',
		attach:['兼用','纤维','油用']
	},
	{
		fieldName:'number_days_childbearing',
		chineseName:'生育日数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[23,135]
	},
	{
		fieldName:'sowing_data',
		chineseName:'播种期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5.09,5.28]
	},
	{
		fieldName:'seeding_stge',
		chineseName:'出苗期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5.21,6.01]
	},
	{
		fieldName:'flowering_stage',
		chineseName:'开花期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6.23,7.21]
	},
	{
		fieldName:'color',
		chineseName:'花色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白粉','白兰','粉','红','兰','兰白','兰紫','浅粉','浅兰','深兰','天兰','紫','紫兰']
	},
	{
		fieldName:'technological_maturity',
		chineseName:'工艺成熟期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7.2,8.15]
	},
	{
		fieldName:'physiological_maturity',
		chineseName:'生理成熟期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.01,8.22]
	},
	{
		fieldName:'drought_resistance',
		chineseName:'抗旱性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'lodging_resistance',
		chineseName:'抗倒伏性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'disease_resistance',
		chineseName:'抗病性',
		type:'select',
		val:'请选择。。。',
		attach:['感','高感','高抗','抗']
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[14,109.7]
	},
	{
		fieldName:'process_length',
		chineseName:'工艺长度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8,98.2]
	},
	{
		fieldName:'number_stems',
		chineseName:'分茎数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,10]
	},
	{
		fieldName:'branch_number',
		chineseName:'分枝数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.4,11.7]
	},
	{
		fieldName:'annual_fruit_number_per_plant',
		chineseName:'单株朔果数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.3,89.8]
	},
	{
		fieldName:'individual_productivity',
		chineseName:'单株生产力',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.21,1.2]
	},
	{
		fieldName:'stem_yiely',
		chineseName:'原茎产量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[75,487.5]
	},
	{
		fieldName:'scapus_yield',
		chineseName:'干茎产量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[67,430.1]
	},
	{
		fieldName:'fiber_yield',
		chineseName:'纤维产量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.6,67.6]
	},
	{
		fieldName:'seed_yield',
		chineseName:'种子产量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10.5,93]
	},
	{
		fieldName:'seed_color',
		chineseName:'种皮色',
		type:'select',
		val:'请选择。。。',
		attach:['白','淡褐','褐','黄','黄白','黄褐','黄绿','深褐','紫红','深黄']
	},
	{
		fieldName:'thousand_grain_weight',
		chineseName:'千粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.1,12.26]
	},
	{
		fieldName:'fibre_strength',
		chineseName:'纤维强度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5.2,30.5]
	},
	{
		fieldName:'fibre_number',
		chineseName:'纤维号',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8,16]
	},
	{
		fieldName:'seed_germination',
		chineseName:'种子发芽',
		type:'compare',
		sel:'=',
		val:'',
		attach:[79,100]
	},
	{
		fieldName:'flax_yield',
		chineseName:'出麻率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.1,21.4]
	},
	{
		fieldName:'oil_yield',
		chineseName:'出油率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[31.41,44.22]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['甘肃','国外','河北','黑龙江','内蒙古','宁夏','青海','山西','新疆']
	}
]