/**
 * 莴笋
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_stage',
		chineseName:'生育期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[36,260]
	},
	{
		fieldName:'maturity',
		chineseName:'熟性',
		type:'select',
		val:'请选择。。。',
		attach:['晚','早','中','中晚']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[22,100]
	},
	{
		fieldName:'strain_amplitude',
		chineseName:'株幅',
		type:'compare',
		sel:'=',
		val:'',
		attach:[14,70.3]
	},
	{
		fieldName:'lobate',
		chineseName:'叶形',
		type:'select',
		val:'请选择。。。',
		attach:['长椭圆','倒卵','卵圆','披针','椭圆','圆形','圆锥']
	},
	{
		fieldName:'leaf',
		chineseName:'叶面',
		type:'select',
		val:'请选择。。。',
		attach:['多皱','平滑','微皱','中']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['红','黄绿','绿','浅绿','深绿','紫']
	},
	{
		fieldName:'pedicel_shape',
		chineseName:'肉茎形状',
		type:'select',
		val:'请选择。。。',
		attach:['倒圆锥','纺锤','棍棒','圆锥']
	},
	{
		fieldName:'pedicel',
		chineseName:'肉茎皮色',
		type:'select',
		val:'请选择。。。',
		attach:['白','褐','红','绿','浅红','浅黄','浅绿','浅紫','深绿','紫']
	},
	{
		fieldName:'pedicel_color',
		chineseName:'肉茎肉色',
		type:'select',
		val:'请选择。。。',
		attach:['白','绿','浅黄','浅绿','深绿']
	},
	{
		fieldName:'fleshy_pedicel',
		chineseName:'肉茎肉质',
		type:'select',
		val:'请选择。。。',
		attach:['脆嫩','多纤维','中']
	},
	{
		fieldName:'pedicel_water',
		chineseName:'肉茎水分',
		type:'select',
		val:'请选择。。。',
		attach:['多','较多','较少','少','中']
	},
	{
		fieldName:'pedicel_weight',
		chineseName:'肉茎重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[50,1000]
	},
	{
		fieldName:'cultivation_season',
		chineseName:'栽培季节',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'disease_resistance_and_insect_resistance',
		chineseName:'抗病虫性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'per_mu_yield',
		chineseName:'亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[428,4500]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
]