/**
 * 绿豆
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family_name',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Leguminosae(豆科)']
	},
	{
		fieldName:'generic_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Vigna(豇豆属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Vigna rabiata (L.) Wilczek(绿豆)']
	},
	{
		fieldName:'breeding_unit',
		chineseName:'选育单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'country_of_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'incubation_year',
		chineseName:'育成年份',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'breeding_methods',
		chineseName:'选育方法',
		type:'select',
		val:'请选择。。。',
		attach:['辐射后代']
	},
	{
		fieldName:'growth_habit',
		chineseName:'生长习性',
		type:'select',
		val:'请选择。。。',
		attach:['半蔓生','蔓生','直立']
	},
	{
		fieldName:'sowing_date',
		chineseName:'播种期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.06,9.21]
	},
	{
		fieldName:'mature_period',
		chineseName:'成熟期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5.2,10.28]
	},
	{
		fieldName:'total_reproductive_days',
		chineseName:'全生育日数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[50,150]
	},
	{
		fieldName:'color',
		chineseName:'花色',
		type:'select',
		val:'请选择。。。',
		attach:['淡黄','黄','黄绿']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[11.8,252]
	},
	{
		fieldName:'branch_number',
		chineseName:'分枝数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,13.7]
	},
	{
		fieldName:'pod_number_per_plant',
		chineseName:'单株荚数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,95]
	},
	{
		fieldName:'number_of_pods_per_pod',
		chineseName:'单荚粒数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.3,163]
	},
	{
		fieldName:'grain_weight_per_plant',
		chineseName:'单株产量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.2,23.7]
	},
	{
		fieldName:'pod_bearing_habit',
		chineseName:'结荚习性',
		type:'select',
		val:'请选择。。。',
		attach:['无限','亚有限','有限']
	},
	{
		fieldName:'pod_color',
		chineseName:'荚色',
		type:'select',
		val:'请选择。。。',
		attach:['橙','褐','褐黑','褐黄','黑','黑褐','黑棕','红黄','黄','黄褐','浅褐','深褐','线褐','棕','棕褐','棕黑']
	},
	{
		fieldName:'pod_length',
		chineseName:'荚长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,20.3]
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['褐','褐（光）','褐（绿）','褐绿','黑','黄','黄（光）','黄褐','黄绿','蓝','绿','绿（光）','青蓝','青蓝光','青兰','棕']
	},
	{
		fieldName:'testa_gloss',
		chineseName:'种皮光泽',
		type:'select',
		val:'请选择。。。',
		attach:['无','有']
	},
	{
		fieldName:'grain_shape',
		chineseName:'粒形',
		type:'select',
		val:'请选择。。。',
		attach:['长圆柱','短圆柱','近球形','圆柱形','球形']
	},
	{
		fieldName:'grain_weight',
		chineseName:'百粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,76]
	},
	{
		fieldName:'protein',
		chineseName:'蛋白质',
		type:'compare',
		sel:'=',
		val:'',
		attach:[17.37,29.06]
	},
	{
		fieldName:'fat',
		chineseName:'脂肪',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.31,1.9]
	},
	{
		fieldName:'total_starch',
		chineseName:'总淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[42.95,60.15]
	},
	{
		fieldName:'amylose',
		chineseName:'直链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7.38,18.84]
	},
	{
		fieldName:'amylopectin',
		chineseName:'支链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[27.42,51.67]
	},
	{
		fieldName:'drought_resistance_at_bud_stage',
		chineseName:'芽期抗旱',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'drought_resistance_in_mature_stage',
		chineseName:'熟期抗旱',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'salt_tolerance_at_bud_stage',
		chineseName:'芽期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'salt_tolerance_in_seedling_stage',
		chineseName:'苗期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'leaf_spot',
		chineseName:'叶斑病级',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'leaf_spot_index',
		chineseName:'叶斑病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[20.6,100]
	},
	{
		fieldName:'leaf_spot_evaluation',
		chineseName:'叶斑病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','MS','S']
	},
	{
		fieldName:'root_rot_class',
		chineseName:'根腐病级',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'root_rot_index',
		chineseName:'根腐病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[45.9,100]
	},
	{
		fieldName:'root_rot_disease_evaluation',
		chineseName:'根腐病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MS','S']
	},
	{
		fieldName:'aphid_index',
		chineseName:'蚜害指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12.5,100]
	},
	{
		fieldName:'the_level_of_aphid_disease',
		chineseName:'蚜害病级别',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,9]
	},
	{
		fieldName:'evaluation_of_diseased_aphids',
		chineseName:'蚜害病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','R','S']
	},
	{
		fieldName:'aphid_ratio',
		chineseName:'蚜害比值',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.34,4.42]
	},
	{
		fieldName:'aspartic_acid',
		chineseName:'天冬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.35,3.87]
	},
	{
		fieldName:'threonine',
		chineseName:'苏氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.67,1.15]
	},
	{
		fieldName:'serine',
		chineseName:'丝氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.81,1.66]
	},
	{
		fieldName:'glutamate',
		chineseName:'谷氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.51,6.47]
	},
	{
		fieldName:'glycine',
		chineseName:'甘氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.78,1.9]
	},
	{
		fieldName:'alanine',
		chineseName:'丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.49,1.76]
	},
	{
		fieldName:'cystine',
		chineseName:'胱氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.06,0.9]
	},
	{
		fieldName:'valine',
		chineseName:'缬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.02,1.93]
	},
	{
		fieldName:'methionine',
		chineseName:'蛋氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.05,0.67]
	},
	{
		fieldName:'isoleucine',
		chineseName:'异亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.31,1.6]
	},
	{
		fieldName:'leucine',
		chineseName:'亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.09,2.67]
	},
	{
		fieldName:'tyrosine',
		chineseName:'酪氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.36,1.11]
	},
	{
		fieldName:'phenylalanine',
		chineseName:'苯丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.22,2.19]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.97,2.34]
	},
	{
		fieldName:'histidine',
		chineseName:'组氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.15,1.14]
	},
	{
		fieldName:'arginine',
		chineseName:'精氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.61,3.13]
	},
	{
		fieldName:'proline',
		chineseName:'脯氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.14,1.98]
	},
	{
		fieldName:'typtophan',
		chineseName:'色氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,0.26]
	},
	{
		fieldName:'the_sum',
		chineseName:'总和',
		type:'compare',
		sel:'=',
		val:'',
		attach:[19.7,31.56]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育']
	},
]