/**
 * 燕麦
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Gramineae(禾本科)']
	},
	{
		fieldName:'the_genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Avena(燕麦属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Avena fatua L.(野燕麦)','Avena magna Tyrphy(大燕麦)','Avena nuda L.(裸燕麦)','Avena sativa L.(普通燕麦)']
	},
	{
		fieldName:'country_of_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'select',
		val:'请选择。。。',
		attach:['河北省坝上农科所','内蒙古农科院','内蒙古乌盟农科所','内蒙古锡盟农科所','青海省农科院','青海省畜牧兽科院','中国农科院草原所','山西省高寒作物所','中国农科院品资所']
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'bare_skin',
		chineseName:'皮裸',
		type:'select',
		val:'请选择。。。',
		attach:['裸','皮']
	},
	{
		fieldName:'number_of_days_of_childbearing',
		chineseName:'生育日数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[74,124]
	},
	{
		fieldName:'seedling_habit',
		chineseName:'幼苗习性',
		type:'select',
		val:'请选择。。。',
		attach:['直立','中','匍伏']
	},
	{
		fieldName:'seedling_color',
		chineseName:'幼苗颜色',
		type:'select',
		val:'请选择。。。',
		attach:['淡绿','绿','深绿']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[53.2,175.4]
	},
	{
		fieldName:'effective_tillering',
		chineseName:'有效分蘖',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,7.6]
	},
	{
		fieldName:'flag_leaf_and_leaf_phase',
		chineseName:'旗叶叶相',
		type:'select',
		val:'请选择。。。',
		attach:['平展','上举','下披']
	},
	{
		fieldName:'spike',
		chineseName:'穗形',
		type:'select',
		val:'请选择。。。',
		attach:['侧紧','侧散','周紧','周散']
	},
	{
		fieldName:'length_of_main_panicle',
		chineseName:'主穗长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[9,41.8]
	},
	{
		fieldName:'spikelet_shape',
		chineseName:'小穗形',
		type:'select',
		val:'请选择。。。',
		attach:['串铃','纺锤']
	},
	{
		fieldName:'spikelet_number_of_main_panicle',
		chineseName:'主穗小穗数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.8,88.5]
	},
	{
		fieldName:'palea_color',
		chineseName:'内稃色',
		type:'select',
		val:'请选择。。。',
		attach:['白','褐','褐黄','黑','黄','浅黑','浅黄']
	},
	{
		fieldName:'lemma_color',
		chineseName:'外稃色',
		type:'select',
		val:'请选择。。。',
		attach:['白','褐','黄','淡黄']
	},
	{
		fieldName:'wheel_number',
		chineseName:'轮层数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.8,9]
	},
	{
		fieldName:'grain_type',
		chineseName:'粒型',
		type:'select',
		val:'请选择。。。',
		attach:['长筒','长圆','纺锤','卵','披纺','披针','椭圆']
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白黄','褐','褐黄','黑','黑黄','红','红黄','红浅黄','花','黄','黄黑','浅褐','浅红','浅黄']
	},
	{
		fieldName:'awn_color',
		chineseName:'芒颜色',
		type:'select',
		val:'请选择。。。',
		attach:['褐','褐黄','黑','黑褐','黑黄','黄','黄黑']
	},
	{
		fieldName:'awn_shape',
		chineseName:'芒形状',
		type:'select',
		val:'请选择。。。',
		attach:['弯','无','直']
	},
	{
		fieldName:'grain_weight_per_plant',
		chineseName:'单株粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.3,9.9]
	},
	{
		fieldName:'grain_weight_per_panicle',
		chineseName:'主穗粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.2,8.9]
	},
	{
		fieldName:'thousand_grain_weight',
		chineseName:'千粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7.4,48.8]
	},
	{
		fieldName:'protein',
		chineseName:'蛋白质',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.71,19.06]
	},
	{
		fieldName:'fat',
		chineseName:'脂肪',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.24,9.82]
	},
	{
		fieldName:'oleic_acid',
		chineseName:'油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[15.64,51.42]
	},
	{
		fieldName:'linoleic_acid',
		chineseName:'亚油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[32.99,51.79]
	},
	{
		fieldName:'linolenic_acid',
		chineseName:'亚麻酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.44,2.31]
	},
	{
		fieldName:'palmitic_acid',
		chineseName:'棕榈酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12.14,48.62]
	},
	{
		fieldName:'fatty_acid',
		chineseName:'占脂肪酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[25.06,47.83]
	},
	{
		fieldName:'unsaturated_fatty_acid',
		chineseName:'不饱脂肪酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[37.26,71.46]
	},
	{
		fieldName:'smut_rate',
		chineseName:'黑穗病率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,100]
	},
	{
		fieldName:'smut_resistance',
		chineseName:'黑穗病抗性',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','IM','MR','MS','R','S']
	},
	{
		fieldName:'red_leaf_disease_grade',
		chineseName:'红叶病病级',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'resistance_to_red_leaf_disease',
		chineseName:'红叶病抗性',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MS','S']
	},
	{
		fieldName:'egg',
		chineseName:'卵块',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.3,10.2]
	},
	{
		fieldName:'larva',
		chineseName:'幼虫',
		type:'compare',
		sel:'=',
		val:'',
		attach:[15.3,283.8]
	},
	{
		fieldName:'aphid',
		chineseName:'蚜虫',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'lodging',
		chineseName:'倒伏性',
		type:'select',
		val:'请选择。。。',
		attach:['低抗','高抗','中抗']
	},
	{
		fieldName:'drought_resistance',
		chineseName:'抗旱性',
		type:'select',
		val:'请选择。。。',
		attach:['低抗','高抗','较强','中抗']
	},
	{
		fieldName:'aspartic_acid',
		chineseName:'天冬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.82,1.76]
	},
	{
		fieldName:'threonine',
		chineseName:'苏氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.37,0.73]
	},
	{
		fieldName:'serine',
		chineseName:'丝氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.4,1]
	},
	{
		fieldName:'glutamate',
		chineseName:'谷氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.59,4.66]
	},
	{
		fieldName:'glycine',
		chineseName:'甘氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.54,1.02]
	},
	{
		fieldName:'alanine',
		chineseName:'丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.51,0.99]
	},
	{
		fieldName:'cystine',
		chineseName:'胱氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,0.48]
	},
	{
		fieldName:'valine',
		chineseName:'缬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.57,1.17]
	},
	{
		fieldName:'methionine',
		chineseName:'蛋氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.18,0.92]
	},
	{
		fieldName:'isoleucine',
		chineseName:'异亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.42,0.86]
	},
	{
		fieldName:'leucine',
		chineseName:'亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.9,1.58]
	},
	{
		fieldName:'tyrosine',
		chineseName:'酪氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.38,0.88]
	},
	{
		fieldName:'phenylalanine',
		chineseName:'苯丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.58,1.19]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.46,0.84]
	},
	{
		fieldName:'ammonia',
		chineseName:'氨',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.12,0.69]
	},
	{
		fieldName:'histidine',
		chineseName:'组氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.22,0.49]
	},
	{
		fieldName:'arginine',
		chineseName:'精氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.47,8.88]
	},
	{
		fieldName:'proline',
		chineseName:'脯氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.42,1.06]
	},
	{
		fieldName:'typtophan',
		chineseName:'色氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.14,0.31]
	},
	{
		fieldName:'the_sum',
		chineseName:'总和',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10.89,20.27]
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育']
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['甘肃','国外','河北','黑龙江','内蒙古','青海','山西','四川']
	},
]