/**
 * 花生
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Leguminosae(豆科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Arachis(落花生属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Arachis appressipila','Arachis chacoense','Arachis correntina','Arachis duranensis','Arachis helodes','Arachis hypogaea L.(花生)','Arachis monticola','Arachis oppressipila','Arachis paraganensis','Arachis pusilla','Arachis rigonii','Arachis sp.','Arachis spegazzinii','Arachis stenoaperma','Arachis stenosperma','Arachis strnosperma','Arachis villosa']
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'unit_number',
		chineseName:'单位编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'breeding_methods',
		chineseName:'选育方法',
		type:'select',
		val:'请选择。。。',
		attach:['地方品种','辐射','混选','激光','考察收集','其他','系选','引种','杂交']
	},
	{
		fieldName:'type',
		chineseName:'类型',
		type:'select',
		val:'请选择。。。',
		attach:['多粒型','龙生型','普通型','其它','珍珠豆型','中间型']
	},
	{
		fieldName:'height_of_main_stem',
		chineseName:'主茎高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.8,107.6]
	},
	{
		fieldName:'plant_type',
		chineseName:'株型',
		type:'select',
		val:'请选择。。。',
		attach:['半蔓','蔓生','直生','匍匐']
	},
	{
		fieldName:'branching_type',
		chineseName:'分枝型',
		type:'select',
		val:'请选择。。。',
		attach:['密枝','疏枝']
	},
	{
		fieldName:'flowering_habit',
		chineseName:'开花习性',
		type:'select',
		val:'请选择。。。',
		attach:['不规则','交替','连续']
	},
	{
		fieldName:'growth_stage',
		chineseName:'生育期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[100,260]
	},
	{
		fieldName:'fruit_weight',
		chineseName:'百果重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7,355]
	},
	{
		fieldName:'kernel_weight',
		chineseName:'百仁重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7.6,137.5]
	},
	{
		fieldName:'shelling_percentage',
		chineseName:'出仁率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[21.3,98.9]
	},
	{
		fieldName:'per_plant_productivity',
		chineseName:'单株生产率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.7,26.5]
	},
	{
		fieldName:'protein_content',
		chineseName:'蛋白质含量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12.48,47.6]
	},
	{
		fieldName:'oil_content',
		chineseName:'含油量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[31.03,60.21]
	},
	{
		fieldName:'palmitic_acid',
		chineseName:'棕榈酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.68,17.61]
	},
	{
		fieldName:'stearic_acid',
		chineseName:'硬脂酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.68,9.36]
	},
	{
		fieldName:'oleic_acid',
		chineseName:'油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[27.17,72.76]
	},
	{
		fieldName:'linoleic_acid',
		chineseName:'亚油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12.55,52.9]
	},
	{
		fieldName:'arachidonic_acid',
		chineseName:'花生酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.18,10.33]
	},
	{
		fieldName:'arachidonice_acid',
		chineseName:'花生烯酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.08,9.53]
	},
	{
		fieldName:'sweet_sour',
		chineseName:'山芋酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.29,5.93]
	},
	{
		fieldName:'leaf_spot',
		chineseName:'抗叶黑斑',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','MR','MS','S']
	},
	{
		fieldName:'leafe_spot',
		chineseName:'抗叶褐斑',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','MR','MS','S']
	},
	{
		fieldName:'bacterial_wilt',
		chineseName:'抗青枯',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','MR','MS','S']
	},
	{
		fieldName:'rust_resistance',
		chineseName:'抗锈病',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','MR','MS','S']
	},
	{
		fieldName:'a_virus',
		chineseName:'病毒病',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','MR','MS']
	},
	{
		fieldName:'resistance_to_root_knot_nematode',
		chineseName:'抗根结线虫',
		type:'select',
		val:'请选择。。。',
		attach:['HR','HS','MR','MS','S']
	},
	{
		fieldName:'combat_drought',
		chineseName:'抗旱',
		type:'select',
		val:'请选择。。。',
		attach:['较强','较弱','强','弱','中']
	},
	{
		fieldName:'waterlogging',
		chineseName:'抗涝',
		type:'select',
		val:'请选择。。。',
		attach:['较强','较弱','强','弱','中']
	},
	{
		fieldName:'aspartic_acid',
		chineseName:'天冬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.19,4.1]
	},
	{
		fieldName:'threonine',
		chineseName:'苏氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.38,1.23]
	},
	{
		fieldName:'serine',
		chineseName:'丝氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.72,1.9]
	},
	{
		fieldName:'glutamate',
		chineseName:'谷氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.98,7.44]
	},
	{
		fieldName:'glycine',
		chineseName:'甘氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.43,2.07]
	},
	{
		fieldName:'alanine',
		chineseName:'丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.45,1.97]
	},
	{
		fieldName:'cystine',
		chineseName:'胱氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.01,0.68]
	},
	{
		fieldName:'valine',
		chineseName:'缬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.44,2.79]
	},
	{
		fieldName:'methionine',
		chineseName:'蛋氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.01,1.24]
	},
	{
		fieldName:'isoleucine',
		chineseName:'异亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,1.93]
	},
	{
		fieldName:'leucine',
		chineseName:'亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.94,3.92]
	},
	{
		fieldName:'tyrosine',
		chineseName:'酪氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.08,1.9]
	},
	{
		fieldName:'phenylalanine',
		chineseName:'苯丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.65,3.01]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.6,1.9]
	},
	{
		fieldName:'histidine',
		chineseName:'组氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.34,1.22]
	},
	{
		fieldName:'arginine',
		chineseName:'精氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.96,6.44]
	},
	{
		fieldName:'proline',
		chineseName:'脯氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.29,2.65]
	},
	{
		fieldName:'typtophan',
		chineseName:'色氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.12,0.55]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
]