/**
 * 豌豆
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family_name',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Leguminosae(豆科)']
	},
	{
		fieldName:'generic_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Pisum(豌豆属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Pisum sativum L.(豌豆)']
	},
	{
		fieldName:'breeding_unit',
		chineseName:'选育单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'country_of_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'incubation_year',
		chineseName:'育成年份',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_habit',
		chineseName:'生长习性',
		type:'select',
		val:'请选择。。。',
		attach:['半蔓生','半直立','蔓生','匍匐','直立']
	},
	{
		fieldName:'sowing_date',
		chineseName:'播种期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.23,11.29]
	},
	{
		fieldName:'mature_period',
		chineseName:'成熟期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.27,9.19]
	},
	{
		fieldName:'total_reproductive_days',
		chineseName:'全生育日数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[65,266]
	},
	{
		fieldName:'color',
		chineseName:'花色',
		type:'select',
		val:'请选择。。。',
		attach:['白','粉','粉红','红','紫','紫红']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12,243]
	},
	{
		fieldName:'branch_number',
		chineseName:'分枝数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,17]
	},
	{
		fieldName:'pod_number_per_plant',
		chineseName:'单株荚数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,95]
	},
	{
		fieldName:'number_of_pods_per_pod',
		chineseName:'单荚粒数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.7,13.6]
	},
	{
		fieldName:'grain_weight_per_plant',
		chineseName:'单株产量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,57.6]
	},
	{
		fieldName:'pod_bearing_habit',
		chineseName:'结荚习性',
		type:'select',
		val:'请选择。。。',
		attach:['无限','有限']
	},
	{
		fieldName:'pod_color',
		chineseName:'荚色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白黄','淡黄','褐','黑','黄','黄白','黄褐','绿']
	},
	{
		fieldName:'pod_length',
		chineseName:'荚长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.2,10.8]
	},
	{
		fieldName:'pod',
		chineseName:'荚型',
		type:'select',
		val:'请选择。。。',
		attach:['半软','软','硬']
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['白','淡红','淡绿','粉红','褐','褐麻','黑','黑麻','黄','绿','麻','浅粉','浅褐','肉黄','深褐']
	},
	{
		fieldName:'grain_shape',
		chineseName:'粒形',
		type:'select',
		val:'请选择。。。',
		attach:['凹圆','扁圆','不规则','不正圆','圆','方形','方皱','椭圆','微圆','微皱','压圆','皱缩']
	},
	{
		fieldName:'grain_weight',
		chineseName:'百粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.5,56.3]
	},
	{
		fieldName:'crude_protein',
		chineseName:'粗蛋白',
		type:'compare',
		sel:'=',
		val:'',
		attach:[15.34,34.64]
	},
	{
		fieldName:'crude_fat',
		chineseName:'粗脂肪',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.14,4.24]
	},
	{
		fieldName:'total_starch',
		chineseName:'总淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[26.95,58.69]
	},
	{
		fieldName:'amylose',
		chineseName:'直链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7.12,24.6]
	},
	{
		fieldName:'amylopectin',
		chineseName:'支链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.61,47.48]
	},
	{
		fieldName:'drought_resistance_at_bud_stage',
		chineseName:'芽期抗旱',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'drought_resistance_in_mature_stage',
		chineseName:'熟期抗旱',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'salt_tolerance_at_bud_stage',
		chineseName:'芽期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'salt_tolerance_in_seedling_stage',
		chineseName:'苗期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,5]
	},
	{
		fieldName:'powdery_mildew_level',
		chineseName:'白粉病级',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'powdery_mildew_index',
		chineseName:'白粉病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.7,100]
	},
	{
		fieldName:'powdery_mildew_evaluation',
		chineseName:'白粉病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','MS','R','S']
	},
	{
		fieldName:'rust_class',
		chineseName:'锈病病级',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'rust_evaluation',
		chineseName:'锈病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','MS','R','S']
	},
	{
		fieldName:'sick_refers_to_aphid',
		chineseName:'蚜害病指',
		type:'compare',
		sel:'=',
		val:'',
		attach:[30,532]
	},
	{
		fieldName:'aphid_sick_level',
		chineseName:'蚜害病级',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'evaluation_of_diseased_aphids',
		chineseName:'蚜害病评价',
		type:'select',
		val:'请选择。。。',
		attach:['HS','MR','MS','R','S']
	},
	{
		fieldName:'aspartic_acid',
		chineseName:'天冬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.81,3.56]
	},
	{
		fieldName:'threonine',
		chineseName:'苏氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.62,1.15]
	},
	{
		fieldName:'serine',
		chineseName:'丝氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.74,1.95]
	},
	{
		fieldName:'glutamate',
		chineseName:'谷氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5,6.22]
	},
	{
		fieldName:'glycine',
		chineseName:'甘氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.68,1.62]
	},
	{
		fieldName:'alanine',
		chineseName:'丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.76,1.46]
	},
	{
		fieldName:'cystine',
		chineseName:'胱氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,1.08]
	},
	{
		fieldName:'valine',
		chineseName:'缬氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.76,1.97]
	},
	{
		fieldName:'methionine',
		chineseName:'蛋氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.05,0.63]
	},
	{
		fieldName:'isoleucine',
		chineseName:'异亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.67,1.72]
	},
	{
		fieldName:'leucine',
		chineseName:'亮氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.16,2.37]
	},
	{
		fieldName:'tyrosine',
		chineseName:'酪氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.27,1.32]
	},
	{
		fieldName:'phenylalanine',
		chineseName:'苯丙氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.35,2.45]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.19,2.24]
	},
	{
		fieldName:'histidine',
		chineseName:'组氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.12,2]
	},
	{
		fieldName:'arginine',
		chineseName:'精氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.51,3.53]
	},
	{
		fieldName:'proline',
		chineseName:'脯氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.34,2.35]
	},
	{
		fieldName:'typtophan',
		chineseName:'色氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.11,0.28]
	},
	{
		fieldName:'the_sum',
		chineseName:'总和',
		type:'compare',
		sel:'=',
		val:'',
		attach:[14.97,30.81]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育']
	},
]