/**
 * 萝卜
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Cruciferae(十字花科)']
	},
	{
		fieldName:'the_genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Raphanus(萝卜属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Raphanus sativus L.(萝卜)']
	},
	{
		fieldName:'breed_origin',
		chineseName:'品种来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'propagation_unit',
		chineseName:'繁种单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'unit_number',
		chineseName:'单位编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_phase',
		chineseName:'生长期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[45,135]
	},
	{
		fieldName:'frondage',
		chineseName:'叶簇',
		type:'select',
		val:'请选择。。。',
		attach:['半开展','半直立','开展','平展','直立']
	},
	{
		fieldName:'leaf_type',
		chineseName:'叶型',
		type:'select',
		val:'请选择。。。',
		attach:['板/花','板叶','花叶']
	},
	{
		fieldName:'lobate',
		chineseName:'叶形',
		type:'select',
		val:'请选择。。。',
		attach:['板叶','长卵圆','长椭圆','倒长卵','椭圆','倒卵圆','倒披针','卵圆']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['黄绿','绿','浅绿','深绿']
	},
	{
		fieldName:'facial_bristle',
		chineseName:'叶面刺毛',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','无','中']
	},
	{
		fieldName:'leaf_lobes',
		chineseName:'叶裂刻',
		type:'select',
		val:'请选择。。。',
		attach:['浅裂','全裂','深裂','无裂']
	},
	{
		fieldName:'lobule_logarithm',
		chineseName:'小裂片对数',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'leaf_length',
		chineseName:'叶片长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4,59]
	},
	{
		fieldName:'blade_width',
		chineseName:'叶片宽',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,21]
	},
	{
		fieldName:'petiole_of_color',
		chineseName:'叶柄色',
		type:'select',
		val:'请选择。。。',
		attach:['红','绿','深紫','浅绿','浅紫','深绿','紫红','紫绿']
	},
	{
		fieldName:'fleshy_root_length',
		chineseName:'肉质根长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,52]
	},
	{
		fieldName:'minister_on_the_ground',
		chineseName:'根地上部长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,25]
	},
	{
		fieldName:'fleshy_root_rough',
		chineseName:'肉质根粗',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,23]
	},
	{
		fieldName:'root_shape',
		chineseName:'根形',
		type:'select',
		val:'请选择。。。',
		attach:['矮圆台','扁圆','长筒','长弯筒','长圆筒','长圆柱','长圆锥','圆锥','短弯筒','短圆筒','短圆锥','纺锤','圆柱','高圆台','近圆','近圆球','梨形','卵圆','炮弹','椭圆','弯圆筒','圆','圆球','圆筒']
	},
	{
		fieldName:'the_root_on_the_skin',
		chineseName:'根地上皮色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白绿','粉红','红','红紫','灰黑','绿','绿白','绿紫','浅绿','浅紫','浅紫红','深红','深绿','桃红','紫','紫红']
	},
	{
		fieldName:'the_root_of_underground',
		chineseName:'根地下皮色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白绿','粉红','红','红紫','灰黑','绿','绿白','绿紫','浅绿','浅紫','浅紫红','深红','深绿','桃红','紫','紫红']
	},
	{
		fieldName:'root_color',
		chineseName:'根肉主色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白带紫','白绿','粉红','红','绿','绿白','浅绿','浅绿白','紫红']
	},
	{
		fieldName:'secondary_color_of_root_meat',
		chineseName:'根肉次色',
		type:'select',
		val:'请选择。。。',
		attach:['白','红','黄','紫']
	},
	{
		fieldName:'root_meat',
		chineseName:'根肉质',
		type:'select',
		val:'请选择。。。',
		attach:['较疏','嫩','脆嫩','疏松','松脆','细嫩','硬','致密','艮硬']
	},
	{
		fieldName:'root_meat_taste',
		chineseName:'根肉口感',
		type:'select',
		val:'请选择。。。',
		attach:['脆嫩','粗松','细面','艮硬']
	},
	{
		fieldName:'root_water_content',
		chineseName:'根肉水分',
		type:'select',
		val:'请选择。。。',
		attach:['多','少','中']
	},
	{
		fieldName:'flavor',
		chineseName:'风味',
		type:'select',
		val:'请选择。。。',
		attach:['辣','稍辣','中辣','甜','甜辣']
	},
	{
		fieldName:'single_weight',
		chineseName:'单根重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[20,3500]
	},
	{
		fieldName:'thousand_grain_weight',
		chineseName:'千粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5,16.5]
	},
	{
		fieldName:'purpose',
		chineseName:'用途',
		type:'select',
		val:'请选择。。。',
		attach:['干制','酱制','生食','生食加工','生熟食','生熟食加工','生熟食腌制','熟食','熟食加工','熟食腌制','腌制','饲用']
	},
	{
		fieldName:'maturity',
		chineseName:'熟性',
		type:'select',
		val:'请选择。。。',
		attach:['极晚','极早','晚','早','中','中晚','中早']
	},
	{
		fieldName:'storability',
		chineseName:'贮藏性',
		type:'select',
		val:'请选择。。。',
		attach:['差','强','中']
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cold_tolerance',
		chineseName:'耐寒性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'drought_tolerance',
		chineseName:'耐旱性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'heat_resistance',
		chineseName:'耐热性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'waterlogging_resistance',
		chineseName:'耐涝性',
		type:'select',
		val:'请选择。。。',
		attach:['强','弱','中']
	},
	{
		fieldName:'disease_resistance',
		chineseName:'抗病性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'insect_resistance',
		chineseName:'抗虫性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivation_period',
		chineseName:'栽培时期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'sowing_date',
		chineseName:'播种期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'harvest_time',
		chineseName:'收获期',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'yield',
		chineseName:'单产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[500,5750]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
]