/**
 * 油菜
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Cruciferae(十字花科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Brassica(芸薹属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Brassica campestris L.(白菜型油菜)','Brassica juncea Czern. et Coss.(芥菜型油菜)','Brassica napus L.(甘蓝型油菜)']
	},
	{
		fieldName:'source',
		chineseName:'来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'altitude',
		chineseName:'高程',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,4641]
	},
	{
		fieldName:'east_longitude',
		chineseName:'东经',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7552,12633]
	},
	{
		fieldName:'north_latitude',
		chineseName:'北纬',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2129,4744]
	},
	{
		fieldName:'type',
		chineseName:'类型',
		type:'select',
		val:'请选择。。。',
		attach:['白菜型','甘蓝型','芥菜型','其他']
	},
	{
		fieldName:'breeding_methods',
		chineseName:'选育方法',
		type:'select',
		val:'请选择。。。',
		attach:['辐射','花培','农家种','系选','野生种','引种','杂交种']
	},
	{
		fieldName:'number_of_days_of_childbearing',
		chineseName:'生育日数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[56,293]
	},
	{
		fieldName:'mature_period',
		chineseName:'成熟期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.19,10.06]
	},
	{
		fieldName:'leaf_type',
		chineseName:'叶型',
		type:'select',
		val:'请选择。。。',
		attach:['花叶','裂叶','浅裂','全裂','深裂','完整']
	},
	{
		fieldName:'color',
		chineseName:'花色',
		type:'select',
		val:'请选择。。。',
		attach:['白','淡黄','淡兰','黄','黄白','金黄','乳白','深黄','鲜黄','紫']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12,273]
	},
	{
		fieldName:'branch_height',
		chineseName:'分枝高度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,186]
	},
	{
		fieldName:'pods',
		chineseName:'全株角果数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5.8,3324.7]
	},
	{
		fieldName:'primary_branch_number',
		chineseName:'一次分枝数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.6,94.1]
	},
	{
		fieldName:'grain_per_fruit',
		chineseName:'每果粒数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,70]
	},
	{
		fieldName:'seed_color',
		chineseName:'种皮色',
		type:'select',
		val:'请选择。。。',
		attach:['淡褐','淡黄','褐','褐黑','褐红','褐黄','黑','黑褐','红','红褐','红黑','花','黄','黄褐','黄黑','黄绿','黄棕','灰黄','深褐','深黄','土黄','五花','紫黑','棕','棕褐','棕黄']
	},
	{
		fieldName:'thousand_grain_weight',
		chineseName:'千粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.48,18.7]
	},
	{
		fieldName:'sclerotinia_sclerotiorum',
		chineseName:'菌核病',
		type:'select',
		val:'请选择。。。',
		attach:['低感','低抗','高感','高抗','中感','中抗']
	},
	{
		fieldName:'a_virus',
		chineseName:'病毒病',
		type:'select',
		val:'请选择。。。',
		attach:['低感','低抗','高感','高抗','中感','中抗']
	},
	{
		fieldName:'downy_mildew',
		chineseName:'霜霉病',
		type:'select',
		val:'请选择。。。',
		attach:['低感','低抗','高感','高抗','免疫','中感','中抗']
	},
	{
		fieldName:'oil_content',
		chineseName:'含油率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[18.7,52.68]
	},
	{
		fieldName:'palmitic_acid',
		chineseName:'棕榈酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,12.65]
	},
	{
		fieldName:'stearic_acid',
		chineseName:'硬脂酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.41,5.48]
	},
	{
		fieldName:'oleic_acid',
		chineseName:'油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5.92,79.97]
	},
	{
		fieldName:'linoleic_acid',
		chineseName:'亚油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6.89,75.68]
	},
	{
		fieldName:'linolenic_acid',
		chineseName:'亚麻酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.52,24.41]
	},
	{
		fieldName:'arachidonic_acid',
		chineseName:'花生烯酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.01,26.14]
	},
	{
		fieldName:'erucic_acid',
		chineseName:'芥酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.01,78.82]
	},
	{
		fieldName:'hydroxyl',
		chineseName:'羟基',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,99.3]
	},
	{
		fieldName:'allyl_group',
		chineseName:'丙烯基',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.16,180.86]
	},
	{
		fieldName:'alkenyl',
		chineseName:'烯基',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.21,18.33]
	},
	{
		fieldName:'x1',
		chineseName:'X1',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.86,442.88]
	},
	{
		fieldName:'butylidene',
		chineseName:'丁烯基',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.47,156.55]
	},
	{
		fieldName:'methyl_indole',
		chineseName:'甲基吲哚',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.42,26.65]
	},
	{
		fieldName:'alkenyl_group',
		chineseName:'戊烯基',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.27,27.73]
	},
	{
		fieldName:'indole',
		chineseName:'吲哚',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.07,16.04]
},
	{
		fieldName:'total',
		chineseName:'总量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[6.06,454.82]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育','野生']
	},
]