/**
 * 水稻
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Gramineae(禾本科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Oryza L.(稻属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Oryza sativa L. f. spontanea(普通栽培稻)','Oryza sativa L. spp. hsien Ting(籼亚种)','Oryza sativa L. spp. keng Ting(粳亚种)']
	},
	{
		fieldName:'altitude',
		chineseName:'高程',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,4352]
	},
	{
		fieldName:'east_longitude',
		chineseName:'东经',
		type:'compare',
		sel:'=',
		val:'',
		attach:[9723,13043]
	},
	{
		fieldName:'north_latitude',
		chineseName:'北纬',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1815,4701]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'country_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'unit_number',
		chineseName:'单位编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'breeding_unit',
		chineseName:'选育单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'method_combination',
		chineseName:'方法及组合',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'breeding_unit',
		chineseName:'籼粳',
		type:'select',
		val:'请选择。。。',
		attach:['粳','籼']
	},
	{
		fieldName:'early_middle_late',
		chineseName:'早中晚',
		type:'select',
		val:'请选择。。。',
		attach:['极早','极晚','早','早中','早晚','中','中早','中中','中晚','晚早','晚中','晚晚']
	},
	{
		fieldName:'amphobious',
		chineseName:'水陆',
		type:'select',
		val:'请选择。。。',
		attach:['陆','水']
	},
	{
		fieldName:'sticky',
		chineseName:'粘糯',
		type:'select',
		val:'请选择。。。',
		attach:['糯','粘']
	},
	{
		fieldName:'beige',
		chineseName:'米色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白、红','白红','白什红','赤','淡红','淡黄','黑','红','红、白','红、红','红、无','红白','黄','浅红','青','乳白','微红','虾肉','紫','紫黑']
	},
	{
		fieldName:'rice',
		chineseName:'米香',
		type:'select',
		val:'请选择。。。',
		attach:['无']
	},
	{
		fieldName:'awn_length',
		chineseName:'芒长',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'grain_shape',
		chineseName:'粒形状',
		type:'select',
		val:'请选择。。。',
		attach:['长椭','短粗','短椭','短圆','阔卵','卵圆','圆','椭圆','细长']
	},
	{
		fieldName:'grain_length',
		chineseName:'粒长度',
		type:'select',
		val:'请选择。。。',
		attach:['长','短','较长','特长','中']
	},
	{
		fieldName:'aspect_ratio',
		chineseName:'长宽比',
		type:'select',
		val:'请选择。。。',
		attach:['宽','窄','中']
	},
	{
		fieldName:'glume_tip_color',
		chineseName:'颖尖色',
		type:'select',
		val:'请选择。。。',
		attach:['长黄','赤褐','淡褐','淡红','淡紫','棕黄','秆黄','褐','杂','黑','黑褐','黑紫','红','红褐','红棕','黄','黄褐','金黄','浓紫','青','乌','无','紫','紫红','紫褐','紫青','紫褐','紫黑']
	},
	{
		fieldName:'glume_color',
		chineseName:'颖壳色',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'breeding_unit',
		chineseName:'颖毛有无',
		type:'select',
		val:'请选择。。。',
		attach:['无','有']
	},
	{
		fieldName:'glume_tip_straight',
		chineseName:'护颖长短',
		type:'select',
		val:'请选择。。。',
		attach:['短']
	},
	{
		fieldName:'Glume_length',
		chineseName:'颖尖弯直',
		type:'select',
		val:'请选择。。。',
		attach:['弯','直']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[42,208.8]
	},
	{
		fieldName:'panicle_emergence_stage',
		chineseName:'出穗期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4.1,11.24]
	},
	{
		fieldName:'brown_rice_percentage',
		chineseName:'糙米率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[52.48,87.14]
	},
	{
		fieldName:'milled_rice_rate',
		chineseName:'精米率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[25.4,79.97]
	},
	{
		fieldName:'chalkiness_rate',
		chineseName:'垩白率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,100]
	},
	{
		fieldName:'protein',
		chineseName:'蛋白质',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4.96,17.16]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.14,0.619]
	},
	{
		fieldName:'total_starch',
		chineseName:'总淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[40.84,91.16]
	},
	{
		fieldName:'amylose',
		chineseName:'直链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.1,77.9]
	},
	{
		fieldName:'amylopectin',
		chineseName:'支链淀粉',
		type:'compare',
		sel:'=',
		val:'',
		attach:[26.2,91]
	},
	{
		fieldName:'temperature',
		chineseName:'糊化温度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,7.6]
	},
	{
		fieldName:'gel_consistency',
		chineseName:'胶稠度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[20,100]
	},
	{
		fieldName:'seeding_blast',
		chineseName:'苗瘟',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'bacterial_blight',
		chineseName:'白叶枯',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'sheath_blight',
		chineseName:'纹枯病',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'brown_planthopper',
		chineseName:'褐稻虱',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'white_backed_planthopper',
		chineseName:'白背飞虱',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'cold_tolerance_bud_stage',
		chineseName:'芽期耐寒',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'drought_tolerance_eedling_tage',
		chineseName:'苗期耐旱',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'salt_tolerance',
		chineseName:'耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育']
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_unit',
		chineseName:'保存单位_2',
		type:'text',
		val:'',
		attach:[]
	}
]