/**
 * 大豆
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Leguminosae(豆科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Glycine(大豆属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Glycine max L. Merrill(大豆)']
	},
	{
		fieldName:'source_of_origin',
		chineseName:'产地来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'altitude',
		chineseName:'高程',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,3741]
	},
	{
		fieldName:'east_longitude',
		chineseName:'东经',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8515,13212]
	},
	{
		fieldName:'north_latitude',
		chineseName:'北纬',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1815,5015]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'type',
		chineseName:'类型',
		type:'select',
		val:'请选择。。。',
		attach:['春','秋','夏']
	},
	{
		fieldName:'birth_month',
		chineseName:'生育月份',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'number_of_days_of_childbearing',
		chineseName:'生育日数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[70,190]
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['鞍挂','暗黄','暗绿','白黄','茶','淡褐','淡黄','淡绿','褐','黑','虎斑','黄','绿','绿黄','浓黄','深褐','紫','双色','乌黑','紫红']
	},
	{
		fieldName:'cotyledon_colour',
		chineseName:'子叶色',
		type:'select',
		val:'请选择。。。',
		attach:['黄','绿']
	},
	{
		fieldName:'hilum_color',
		chineseName:'脐色',
		type:'select',
		val:'请选择。。。',
		attach:['褐','褐黑','褐黄','褐无','黑','黑褐','红褐','黄','黄褐','灰','蓝','浅褐','浅灰','深褐','深灰','无']
	},
	{
		fieldName:'grain_weight',
		chineseName:'百粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.8,35]
	},
	{
		fieldName:'grain_shape',
		chineseName:'粒形',
		type:'select',
		val:'请选择。。。',
		attach:['扁椭','扁圆','长椭','近圆','肾状','椭圆','圆']
	},
	{
		fieldName:'growth_habit',
		chineseName:'生长习性',
		type:'select',
		val:'请选择。。。',
		attach:['半蔓','半直','蔓生','直立']
	},
	{
		fieldName:'pod_bearing_habit',
		chineseName:'结荚习性',
		type:'select',
		val:'请选择。。。',
		attach:['无','亚','有']
	},
	{
		fieldName:'hair_color',
		chineseName:'茸毛色',
		type:'select',
		val:'请选择。。。',
		attach:['灰','灰粽','棕','棕灰','无毛']
	},
	{
		fieldName:'color',
		chineseName:'花色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白紫','紫','紫白']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[11.8,251]
	},
	{
		fieldName:'leaf',
		chineseName:'叶形',
		type:'select',
		val:'请选择。。。',
		attach:['长卵','长椭','卵椭','卵圆','披针','椭圆','圆']
	},
	{
		fieldName:'crude_protein',
		chineseName:'粗蛋白',
		type:'compare',
		sel:'=',
		val:'',
		attach:[30.8,48.9]
	},
	{
		fieldName:'crude_fat',
		chineseName:'粗脂肪',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12.1,25.3]
	},
	{
		fieldName:'cystine',
		chineseName:'胱氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.1,1.6]
	},
	{
		fieldName:'methionine',
		chineseName:'蛋氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,1.5]
	},
	{
		fieldName:'trypsin_inhibitor',
		chineseName:'胰酶抑制剂',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'stearic_acid',
		chineseName:'硬脂酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.8,5.8]
	},
	{
		fieldName:'palmitic_acid',
		chineseName:'软脂酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.6,14.8]
	},
	{
		fieldName:'oleic_acid',
		chineseName:'油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[13.1,43.9]
	},
	{
		fieldName:'linoleic_acid',
		chineseName:'亚油酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[34.8,61.6]
	},
	{
		fieldName:'linolenic_acid',
		chineseName:'亚麻酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4.7,16.7]
	},
	{
		fieldName:'salt_resistance_in_bud_stage',
		chineseName:'芽期抗盐性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,5]
	},
	{
		fieldName:'salt_tolerance_in_seedling_stage',
		chineseName:'苗期抗盐性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'drought_resistance_at_bud_stage',
		chineseName:'芽期抗旱性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,5]
	},
	{
		fieldName:'drought_resistance_at_maturity_stage',
		chineseName:'熟期抗旱性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,5]
	},
	{
		fieldName:'cold_resistance_at_bud_stage',
		chineseName:'芽期抗冷',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'cold_resistance_in_seedling_stage',
		chineseName:'苗期抗冷',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'virus_index',
		chineseName:'病毒指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.27,100]
	},
	{
		fieldName:'virus_level',
		chineseName:'病毒等级',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'rust_resistance',
		chineseName:'锈病抗病性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'rust_responsive',
		chineseName:'锈病反应型',
		type:'select',
		val:'请选择。。。',
		attach:['R-N','S-L','S-S']
	},
	{
		fieldName:'rust_rank',
		chineseName:'锈病等级',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,9]
	},
	{
		fieldName:'average_cyst_1',
		chineseName:'平均孢囊1',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,61.7]
	},
	{
		fieldName:'cyst_grade_1',
		chineseName:'孢囊等级1',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'average_cyst_2',
		chineseName:'平均孢囊2',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.5,30]
	},
	{
		fieldName:'cyst_grade_2',
		chineseName:'孢囊等级2',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,9]
	},
	{
		fieldName:'average_cyst_3',
		chineseName:'平均孢囊3',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.1,100]
	},
	{
		fieldName:'cyst_index_3',
		chineseName:'孢囊指数3',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.01,0.01]
	},
	{
		fieldName:'cyst_grade_3',
		chineseName:'孢囊等级3',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,7]
	},
	{
		fieldName:'average_cyst_4',
		chineseName:'平均孢囊4',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.4,100]
	},
	{
		fieldName:'cyst_grade_4',
		chineseName:'孢囊等级4',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,9]
	},
	{
		fieldName:'average_cyst_5',
		chineseName:'平均孢囊5',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.2,95]
	},
	{
		fieldName:'cyst_grade_5',
		chineseName:'孢囊等级5',
		type:'compare',
		sel:'=',
		val:'',
		attach:[5,9]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'area',
		chineseName:'区',
		type:'select',
		val:'请选择。。。',
		attach:['北方春大豆','东北春大豆','黄淮春大豆','黄淮夏大豆','南方春大豆','南方秋大豆','南方夏大豆']
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','选育']
	},
]