/**
 * 向日葵
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Gramineae(禾本科)']
	},
	{
		fieldName:'the_genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Zea(玉米属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Zea mays L.(玉米)']
	},
	{
		fieldName:'country_of_origin',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'number',
		chineseName:'编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'type',
		chineseName:'类型',
		type:'select',
		val:'请选择。。。',
		attach:['半野生','观赏','兼用','食用','野生','油用','中间']
	},
	{
		fieldName:'birth_date',
		chineseName:'生育日期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[75,183]
	},
	{
		fieldName:'hypocotyl_colour',
		chineseName:'胚轴色',
		type:'select',
		val:'请选择。。。',
		attach:['淡红','淡绿','淡紫','红','绿','绿紫','深紫','紫','紫黑','紫绿']
	},
	{
		fieldName:'young_stem_color',
		chineseName:'幼茎色',
		type:'select',
		val:'请选择。。。',
		attach:['白','淡红','淡绿','淡紫','红','绿','绿红','绿紫','深紫','无','紫','紫红','紫绿']
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[30,350]
	},
	{
		fieldName:'blade_number',
		chineseName:'叶片数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10,95]
	},
	{
		fieldName:'branch_rate',
		chineseName:'分枝株率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.8,100]
	},
	{
		fieldName:'ligulate_flower',
		chineseName:'舌状花色',
		type:'select',
		val:'请选择。。。',
		attach:['橙','橙黄','淡黄','黄','黄紫','深黄','紫','紫红']
	},
	{
		fieldName:'stigma_color',
		chineseName:'柱头色',
		type:'select',
		val:'请选择。。。',
		attach:['白','橙黄','淡褐','淡黄','淡紫','褐','黄','黄褐','黄红','黄绿','深褐','深黄','微红','紫','紫红','紫黄','棕红']
	},
	{
		fieldName:'disk_inclination',
		chineseName:'花盘倾斜度',
		type:'select',
		val:'请选择。。。',
		attach:['0','1','2','3','4','5']
	},
	{
		fieldName:'disk_shape',
		chineseName:'花盘形状',
		type:'select',
		val:'请选择。。。',
		attach:['凹','平','平凹','平凸','凸','微凸']
	},
	{
		fieldName:'disk_diameter',
		chineseName:'花盘直径',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.3,36.1]
	},
	{
		fieldName:'grain_shape',
		chineseName:'粒形',
		type:'select',
		val:'请选择。。。',
		attach:['长剑','长宽锥','长卵','长卵圆','长锲','大','短宽锥','短卵','短卵圆','短锲','短圆','短圆锥','短锥','宽锥','卵形','卵圆','卵锥','特短锲','特短锥','小','圆锥','中长锥','中剑','中宽锥','中卵','中锲','中锥']
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白边黑','白黑','白黑条','白黑纹','白花','白黑条','白灰','白灰点','白灰条','白灰纹','白棕','白棕边','淡灰','褐','褐白边','褐白条','褐白纹','褐黑','褐黑条','褐黄','褐灰条','褐灰纹','褐棕条','黑','黑暗条','黑暗条纹','黑白','黑白边','黑白花','黑白花条','黑白条','黑白纹','黑褐','黑褐边','黑褐条','黑褐条边','黑褐纹','黑花','黑黄条','黑灰','黑灰白边','黑灰边','黑灰条','黑灰条纹','黑灰纹','黑条纹','黑纹','黑紫','黑紫边','黑紫条','黑棕','黑棕边','黑棕条','黑棕纹','红黑','花','黄白条','黄褐','黄黑','灰','灰白','灰白边','灰白花','灰白条','灰白纹','灰褐','灰黑','灰黑白条纹','灰黑点','灰黑条','灰黑条纹','灰黑点','灰黑条','灰黑条纹','灰黑纹','灰黄','灰条纹','灰粽边','灰粽纹','墨黑','浅黑','浅灰白','紫','紫黑','紫黑条','紫灰边','棕','棕白','棕白边','棕白条','棕白纹','棕黑','棕黑条','棕黑纹','棕红','棕黄','棕黄条','棕灰','棕灰条','棕灰纹']
	},
	{
		fieldName:'seed_weight_per_plant',
		chineseName:'单株子实重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.23,960]
	},
	{
		fieldName:'grain_weight',
		chineseName:'百粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.5,88.4]
	},
	{
		fieldName:'the_rate_of_hull',
		chineseName:'皮壳率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10,70.8]
	},
	{
		fieldName:'grain_oil_content',
		chineseName:'子实含油率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[12.3,59.83]
	},
	{
		fieldName:'crude_protein_content',
		chineseName:'粗蛋白含量',
		type:'compare',
		sel:'=',
		val:'',
		attach:[9.7,36.4]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	}
]