/**
 * 西红柿\番茄
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'germplasm_bank_number',
		chineseName:'种质库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'seed_source',
		chineseName:'种子来源',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'save_number',
		chineseName:'保存编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'growth_stage',
		chineseName:'生育期',
		type:'compare',
		sel:'=',
		val:'',
		attach:[30,160]
	},
	{
		fieldName:'maturity',
		chineseName:'熟性',
		type:'select',
		val:'请选择。。。',
		attach:['晚熟','早熟','中熟']
	},
	{
		fieldName:'plant_type',
		chineseName:'株型',
		type:'select',
		val:'请选择。。。',
		attach:['矮生','半蔓生','蔓生']
	},
	{
		fieldName:'growth_habit',
		chineseName:'生长习性',
		type:'select',
		val:'请选择。。。',
		attach:['无限','有限','有限无限']
	},
	{
		fieldName:'leaf_type',
		chineseName:'叶型',
		type:'select',
		val:'请选择。。。',
		attach:['马铃薯叶','普通叶']
	},
	{
		fieldName:'leaf_color',
		chineseName:'叶色',
		type:'select',
		val:'请选择。。。',
		attach:['黄','绿','浅绿','深绿']
	},
	{
		fieldName:'initial_floral_node',
		chineseName:'始花节位',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3,14]
	},
	{
		fieldName:'fruit_shape',
		chineseName:'果形',
		type:'select',
		val:'请选择。。。',
		attach:['扁形','梨形','其他形','心脏形','圆形']
	},
	{
		fieldName:'single_fruit_weight',
		chineseName:'单果重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10,400]
	},
	{
		fieldName:'mature_fruit',
		chineseName:'成熟果皮色',
		type:'select',
		val:'请选择。。。',
		attach:['红','黄','黄和红','桔红','桔黄','绿']
	},
	{
		fieldName:'fruit_flesh',
		chineseName:'果肉色',
		type:'select',
		val:'请选择。。。',
		attach:['红','黄','黄和红','桔红','桔黄','绿']
	},
	{
		fieldName:'fruit_surface_characteristics',
		chineseName:'果面特征',
		type:'select',
		val:'请选择。。。',
		attach:['棱沟','平滑']
	},
	{
		fieldName:'the_size_of',
		chineseName:'果脐大小',
		type:'select',
		val:'请选择。。。',
		attach:['大','小','中']
	},
	{
		fieldName:'meat_quality',
		chineseName:'肉质',
		type:'select',
		val:'请选择。。。',
		attach:['脆','脆多汁','多汁','面','面多汁','软','软不面','软多汁','软面','细','细面','纤维多','致密','致密多汁','中','中软']
	},
	{
		fieldName:'flavor',
		chineseName:'风味',
		type:'select',
		val:'请选择。。。',
		attach:['不酸','淡','淡酸','淡甜','好','较酸','较甜','浓','酸','酸甜','甜','甜淡','微酸','微甜','香味','中']
	},
	{
		fieldName:'purpose',
		chineseName:'用途',
		type:'select',
		val:'请选择。。。',
		attach:['加工','鲜食','鲜食加工']
	},
	{
		fieldName:'cultivation_season',
		chineseName:'栽培季节',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'stress_resistance',
		chineseName:'抗逆性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'disease_resistance_and_insect_resistance',
		chineseName:'抗病虫性',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'per_mu_yield',
		chineseName:'亩产',
		type:'compare',
		sel:'=',
		val:'',
		attach:[200,8500]
	},
	{
		fieldName:'remarks',
		chineseName:'备注',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
]