/**
 * 小麦
 * 查询模型
 * {
		fieldName:'library_number',     //字段名，对应数据库中的字段名
		chineseName:'库编号',           //中文名，该字段的中文名
		type:'text',                    //查询类型，有三个类型：text,select,compare
		attach:[]                       //附件条件。当查询类型为text时，此字段无意义；当为select时，此字段为选项数组；当为compare时，此字段为输入区间的最小值、最大值
	}
 */
module.exports = [
	{
		fieldName:'library_number',
		chineseName:'库编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'uniform_number',
		chineseName:'统一编号',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'preservation_unit',
		chineseName:'保存单位',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'cultivar_name',
		chineseName:'品种名称',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'translation',
		chineseName:'译名',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'family',
		chineseName:'科名',
		type:'select',
		val:'请选择。。。',
		attach:['Gramineae(禾本科)']
	},
	{
		fieldName:'genus_name',
		chineseName:'属名',
		type:'select',
		val:'请选择。。。',
		attach:['Triticum L.(小麦属)']
	},
	{
		fieldName:'name',
		chineseName:'学名',
		type:'select',
		val:'请选择。。。',
		attach:['Triticum aestivum L.(普通小麦)']
	},
	{
		fieldName:'pedigree',
		chineseName:'系谱',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'incubation_years',
		chineseName:'育成年限',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1962,1992]
	},
	{
		fieldName:'country_of_origines',
		chineseName:'原产地',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'altitude',
		chineseName:'高程',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,4641]
	},
	{
		fieldName:'east_longitude',
		chineseName:'东经',
		type:'compare',
		sel:'=',
		val:'',
		attach:[7552,13159]
	},
	{
		fieldName:'north_latitude',
		chineseName:'北纬',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2221,5015]
	},
	{
		fieldName:'country_of_origin',
		chineseName:'来源国',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'awn',
		chineseName:'芒',
		type:'select',
		val:'请选择。。。',
		attach:['半长','长','长勾曲','长黑','长曲','长拳','顶','顶无','短','短曲','短拳','勾','勾曲','黑长','黑顶','黑短','黑短曲','黑毛','墨长','曲','拳','微','无','有','中','中长']
	},
	{
		fieldName:'shell_color',
		chineseName:'壳色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白底黑壳','白黑','白红','白毛','褐','黑','黑白','黑褐','黑红','黑黄','黑毛','黑紫','红','红底黑','红褐','红黑','红壳黑边','红毛','花','黄','灰','灰红','灰毛','浅红','鼠灰壳白底','鼠灰壳白底','鼠灰壳红底','鼠灰壳红毛','紫','紫黑']
	},
	{
		fieldName:'grain_color',
		chineseName:'粒色',
		type:'select',
		val:'请选择。。。',
		attach:['白','白红','淡红','红','红白','黄','紫','琥珀']
	},{
		fieldName:'spring_and_winter',
		chineseName:'冬春性',
		type:'select',
		val:'请选择。。。',
		attach:['半冬','春','冬','偏春','强春','强冬','弱冬']
	},
	{
		fieldName:'maturation_period',
		chineseName:'成熟期',
		type:'select',
		val:'请选择。。。',
		attach:['极晚','极早','特早','晚','早','中','中晚','中早']
	},
	{
		fieldName:'grain_number_per_panicle',
		chineseName:'穗粒数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[11,120]
	},
	{
		fieldName:'spike_length',
		chineseName:'穗长',
		type:'compare',
		sel:'=',
		val:'',
		attach:[3.4,19.8]
	},
	{
		fieldName:'plant_height',
		chineseName:'株高',
		type:'compare',
		sel:'=',
		val:'',
		attach:[22,191]
	},
	{
		fieldName:'thousand_kerner_weight',
		chineseName:'千粒重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.1,59.9]
	},
	{
		fieldName:'crude_protein',
		chineseName:'粗蛋白',
		type:'compare',
		sel:'=',
		val:'',
		attach:[8.74,24.15]
	},
	{
		fieldName:'lysine',
		chineseName:'赖氨酸',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0.27,0.72]
	},
	{
		fieldName:'lysinesedimentation_value',
		chineseName:'沉淀值',
		type:'compare',
		sel:'=',
		val:'',
		attach:[4.0,70.9]
	},
	{
		fieldName:'hardness',
		chineseName:'硬度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[9.4,619.4]
	},
	{
		fieldName:'bulk_density',
		chineseName:'容重',
		type:'compare',
		sel:'=',
		val:'',
		attach:[543.0,865.5]
	},
	{
		fieldName:'drought_resistance',
		chineseName:'抗旱性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'waterlogging_resistance',
		chineseName:'耐涝性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'salt_tolerance_at_bud_stage',
		chineseName:'芽期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'salt_lerance_seedling_stage',
		chineseName:'苗期耐盐',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'field_cold_resistance',
		chineseName:'田间抗寒性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'artificial_cold_resistance',
		chineseName:'人工抗寒性',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,5]
	},
	{
		fieldName:'stripe_rust_severity',
		chineseName:'条锈严重度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,100]
	},
	{
		fieldName:'rust_reaction_type',
		chineseName:'条锈反应型',
		type:'select',
		val:'请选择。。。',
		attach:['0','MR','MS','R','S']
	},
	{
		fieldName:'iniversal_rate_of_stripe_rust',
		chineseName:'条锈普遍率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,100]
	},
	{
		fieldName:'leaf_rust_severity',
		chineseName:'叶锈严重度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,100]
	},
	{
		fieldName:'leaf_rust_reaction_type',
		chineseName:'叶锈反应型',
		type:'select',
		val:'请选择。。。',
		attach:['0','MR','MS','R','S']
	},
	{
		fieldName:'leaf_rust_prevalence',
		chineseName:'叶锈普遍率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,100]
	},
	{
		fieldName:'culm_rust_severity',
		chineseName:'秆锈严重度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1,100]
	},
	{
		fieldName:'culm_rust_reaction_type',
		chineseName:'秆锈反应型',
		type:'select',
		val:'请选择。。。',
		attach:['0','MR','MS','R','S']
	},
	{
		fieldName:'culm_rest_prevalence',
		chineseName:'秆锈普遍率',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2,100]
	},
	{
		fieldName:'white_powder_severity',
		chineseName:'白粉严重度',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,9]
	},
	{
		fieldName:'white_powder_reaction_type',
		chineseName:'白粉反应型',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,5]
	},
	{
		fieldName:'yellow_dwarf',
		chineseName:'黄矮病',
		type:'compare',
		sel:'=',
		val:'',
		attach:[0,9]
	},
	{
		fieldName:'gibberellic_disease_rice',
		chineseName:'赤霉病病穗',
		type:'compare',
		sel:'=',
		val:'',
		attach:[10.0,100.0]
	},
	{
		fieldName:'gibberellic_disease_target',
		chineseName:'赤霉病病指',
		type:'compare',
		sel:'=',
		val:'',
		attach:[2.5,100]
	},
	{
		fieldName:'gibberellic_disease_index',
		chineseName:'赤霉病指数',
		type:'compare',
		sel:'=',
		val:'',
		attach:[1.0,5.0]
	},
	{
		fieldName:'gibberellic_disease',
		chineseName:'赤霉病抗性',
		type:'select',
		val:'请选择。。。',
		attach:['MR','MS','R','S']
	},
	{
		fieldName:'root_rot_and_leaf_disease',
		chineseName:'根腐叶病级',
		type:'select',
		val:'请选择。。。',
		attach:['MR','MS','R','S']
	},
	{
		fieldName:'root_rot_disease_grade',
		chineseName:'根腐穗病级',
		type:'select',
		val:'请选择。。。',
		attach:['0','MR','MS','R','S']
	},
	{
		fieldName:'other',
		chineseName:'其他',
		type:'text',
		val:'',
		attach:[]
	},
	{
		fieldName:'province',
		chineseName:'省',
		type:'select',
		val:'请选择。。。',
		attach:['安徽','北京','福建','甘肃','广东','广西','贵州','国外','河北','河南','黑龙江','湖北','湖南','吉林','江苏','江西','辽宁','内蒙古','宁夏','青海','山东','山西','陕西','上海','四川','台湾','天津','西藏','新疆','云南','浙江']
	},
	{
		fieldName:'sample_type',
		chineseName:'样品类型',
		type:'select',
		val:'请选择。。。',
		attach:['地方','国外','选育']
	}
]